//
//  OvalDefinitionsSchemaTypeinfo.hpp
//  ConformeOVAL
//
//  Created by Thomas on 1/30/18.
//  Copyright © 2018 Thomas Jones. All rights reserved.
//


#ifndef _CONFORME_INCLUDED_OVAL_DEFINITIONS_SCHEMA_TYPEINFO_H_
#define _CONFORME_INCLUDED_OVAL_DEFINITIONS_SCHEMA_TYPEINFO_H_

#include <Conforme/StructureInformation.hpp>


#undef CONFORME_OVAL_DECLSPECIFIER

#if !defined( __GNUC__ )
#ifdef OVAL_DEFINITIONS_SCHEMA_EXPORTS
#define CONFORME_OVAL_DECLSPECIFIER __declspec(dllexport)
#else
#define CONFORME_OVAL_DECLSPECIFIER __declspec(dllimport)
#endif
#else
#define CONFORME_OVAL_DECLSPECIFIER
#endif


namespace oval_definitions_schema
{

enum conforme_namespace_indices
{
	conforme_namespace_indice_oval,		
	conforme_namespace_indice_oval_def,		
	conforme_namespace_indice_xmldsig,		
	conforme_namespace_indice_xmlschema,		

};

enum conforme_type_indices
{
	conforme_ti_oval_first,
	conforme_ti_oval_CCheckEnumeration = conforme_ti_oval_first,
	conforme_ti_oval_CClassEnumeration,
	conforme_ti_oval_CComplexDatatypeEnumeration,
	conforme_ti_oval_CDatatypeEnumeration,
	conforme_ti_oval_CDefinitionIDPattern,
	conforme_ti_oval_CDeprecatedInfoType,
	conforme_ti_oval_CElementMapItemType,
	conforme_ti_oval_CElementMapType,
	conforme_ti_oval_CEmptyStringType,
	conforme_ti_oval_CExistenceEnumeration,
	conforme_ti_oval_CFamilyEnumeration,
	conforme_ti_oval_CGeneratorType,
	conforme_ti_oval_CItemIDPattern,
	conforme_ti_oval_CMessageLevelEnumeration,
	conforme_ti_oval_CMessageType,
	conforme_ti_oval_CNonEmptyStringType,
	conforme_ti_oval_CNotesType,
	conforme_ti_oval_CObjectIDPattern,
	conforme_ti_oval_COperationEnumeration,
	conforme_ti_oval_COperatorEnumeration,
	conforme_ti_oval_CSchemaVersionPattern,
	conforme_ti_oval_CSchemaVersionType,
	conforme_ti_oval_CSimpleDatatypeEnumeration,
	conforme_ti_oval_CStateIDPattern,
	conforme_ti_oval_CTestIDPattern,
	conforme_ti_oval_CVariableIDPattern,
	conforme_ti_oval_CStateIDPatternType,
	conforme_ti_oval_CObjectIDPatternType,
	conforme_ti_oval_CversionType,
	conforme_ti_oval_CversionType2,
	conforme_ti_oval_CSchemaVersionPatternType,
	conforme_ti_oval_last,

	conforme_ti_oval_def_first = conforme_ti_oval_last,
	conforme_ti_oval_def_CAffectedType = conforme_ti_oval_def_first,
	conforme_ti_oval_def_CArithmeticEnumeration,
	conforme_ti_oval_def_CArithmeticFunctionType,
	conforme_ti_oval_def_CBeginFunctionType,
	conforme_ti_oval_def_CConcatFunctionType,
	conforme_ti_oval_def_CCountFunctionType,
	conforme_ti_oval_def_CCriteriaType,
	conforme_ti_oval_def_CCriterionType,
	conforme_ti_oval_def_CDateTimeFormatEnumeration,
	conforme_ti_oval_def_CDefinitionType,
	conforme_ti_oval_def_CDefinitionsType,
	conforme_ti_oval_def_CEndFunctionType,
	conforme_ti_oval_def_CEntityComplexBaseType,
	conforme_ti_oval_def_CEntityObjectAnySimpleType,
	conforme_ti_oval_def_CEntityObjectBinaryType,
	conforme_ti_oval_def_CEntityObjectBoolType,
	conforme_ti_oval_def_CEntityObjectFieldType,
	conforme_ti_oval_def_CEntityObjectFloatType,
	conforme_ti_oval_def_CEntityObjectIPAddressStringType,
	conforme_ti_oval_def_CEntityObjectIPAddressType,
	conforme_ti_oval_def_CEntityObjectIntType,
	conforme_ti_oval_def_CEntityObjectRecordType,
	conforme_ti_oval_def_CEntityObjectStringType,
	conforme_ti_oval_def_CEntityObjectVersionType,
	conforme_ti_oval_def_CEntitySimpleBaseType,
	conforme_ti_oval_def_CEntityStateAnySimpleType,
	conforme_ti_oval_def_CEntityStateBinaryType,
	conforme_ti_oval_def_CEntityStateBoolType,
	conforme_ti_oval_def_CEntityStateComplexBaseType,
	conforme_ti_oval_def_CEntityStateDebianEVRStringType,
	conforme_ti_oval_def_CEntityStateEVRStringType,
	conforme_ti_oval_def_CEntityStateFieldType,
	conforme_ti_oval_def_CEntityStateFileSetRevisionType,
	conforme_ti_oval_def_CEntityStateFloatType,
	conforme_ti_oval_def_CEntityStateIOSVersionType,
	conforme_ti_oval_def_CEntityStateIPAddressStringType,
	conforme_ti_oval_def_CEntityStateIPAddressType,
	conforme_ti_oval_def_CEntityStateIntType,
	conforme_ti_oval_def_CEntityStateRecordType,
	conforme_ti_oval_def_CEntityStateSimpleBaseType,
	conforme_ti_oval_def_CEntityStateStringType,
	conforme_ti_oval_def_CEntityStateVersionType,
	conforme_ti_oval_def_CEscapeRegexFunctionType,
	conforme_ti_oval_def_CExtendDefinitionType,
	conforme_ti_oval_def_CFilterActionEnumeration,
	conforme_ti_oval_def_CGlobToRegexFunctionType,
	conforme_ti_oval_def_CLiteralComponentType,
	conforme_ti_oval_def_CMetadataType,
	conforme_ti_oval_def_CObjectComponentType,
	conforme_ti_oval_def_CObjectRefType,
	conforme_ti_oval_def_CObjectType,
	conforme_ti_oval_def_CObjectsType,
	conforme_ti_oval_def_CPossibleRestrictionType,
	conforme_ti_oval_def_CPossibleValueType,
	conforme_ti_oval_def_CReferenceType,
	conforme_ti_oval_def_CRegexCaptureFunctionType,
	conforme_ti_oval_def_CRestrictionType,
	conforme_ti_oval_def_CSetOperatorEnumeration,
	conforme_ti_oval_def_CSplitFunctionType,
	conforme_ti_oval_def_CStateRefType,
	conforme_ti_oval_def_CStateType,
	conforme_ti_oval_def_CStatesType,
	conforme_ti_oval_def_CSubstringFunctionType,
	conforme_ti_oval_def_CTestType,
	conforme_ti_oval_def_CTestsType,
	conforme_ti_oval_def_CTimeDifferenceFunctionType,
	conforme_ti_oval_def_CUniqueFunctionType,
	conforme_ti_oval_def_CValueType,
	conforme_ti_oval_def_CVariableComponentType,
	conforme_ti_oval_def_CVariableType,
	conforme_ti_oval_def_CVariablesType,
	conforme_ti_oval_def_Coval_definitions_schema,
	conforme_ti_oval_def_Cconstant_variableType,
	conforme_ti_oval_def_CnotesType,
	conforme_ti_oval_def_Cexternal_variableType,
	conforme_ti_oval_def_CfilterType,
	conforme_ti_oval_def_Clocal_variableType,
	conforme_ti_oval_def_Coval_definitionsType,
	conforme_ti_oval_def_CsetType,
	conforme_ti_oval_def_CnameType,
	conforme_ti_oval_def_CdatatypeType,
	conforme_ti_oval_def_CdatatypeType2,
	conforme_ti_oval_def_CnameType2,
	conforme_ti_oval_def_CdatatypeType3,
	conforme_ti_oval_def_CdatatypeType4,
	conforme_ti_oval_def_CdatatypeType5,
	conforme_ti_oval_def_last,

	conforme_ti_xmldsig_first = conforme_ti_oval_def_last,
	conforme_ti_xmldsig_CCanonicalizationMethodType = conforme_ti_xmldsig_first,
	conforme_ti_xmldsig_CCryptoBinary,
	conforme_ti_xmldsig_CDSAKeyValueType,
	conforme_ti_xmldsig_CDigestMethodType,
	conforme_ti_xmldsig_CDigestValueType,
	conforme_ti_xmldsig_CHMACOutputLengthType,
	conforme_ti_xmldsig_CKeyInfoType,
	conforme_ti_xmldsig_CKeyValueType,
	conforme_ti_xmldsig_CManifestType,
	conforme_ti_xmldsig_CObjectType,
	conforme_ti_xmldsig_CPGPDataType,
	conforme_ti_xmldsig_CRSAKeyValueType,
	conforme_ti_xmldsig_CReferenceType,
	conforme_ti_xmldsig_CRetrievalMethodType,
	conforme_ti_xmldsig_CSPKIDataType,
	conforme_ti_xmldsig_CSignatureMethodType,
	conforme_ti_xmldsig_CSignaturePropertiesType,
	conforme_ti_xmldsig_CSignaturePropertyType,
	conforme_ti_xmldsig_CSignatureType,
	conforme_ti_xmldsig_CSignatureValueType,
	conforme_ti_xmldsig_CSignedInfoType,
	conforme_ti_xmldsig_CTransformType,
	conforme_ti_xmldsig_CTransformsType,
	conforme_ti_xmldsig_CX509DataType,
	conforme_ti_xmldsig_CX509IssuerSerialType,
	conforme_ti_xmldsig_CDigestValueTypeType,
	conforme_ti_xmldsig_CCryptoBinaryType,
	conforme_ti_xmldsig_CHMACOutputLengthTypeType,
	conforme_ti_xmldsig_last,

	conforme_ti_xmlschema_first = conforme_ti_xmldsig_last,
	conforme_ti_xmlschema_CENTITIES = conforme_ti_xmlschema_first,
	conforme_ti_xmlschema_CENTITY,
	conforme_ti_xmlschema_CID,
	conforme_ti_xmlschema_CIDREF,
	conforme_ti_xmlschema_CIDREFS,
	conforme_ti_xmlschema_CNCName,
	conforme_ti_xmlschema_CNMTOKEN,
	conforme_ti_xmlschema_CNMTOKENS,
	conforme_ti_xmlschema_CNOTATION,
	conforme_ti_xmlschema_CName,
	conforme_ti_xmlschema_CQName,
	conforme_ti_xmlschema_CanySimpleType,
	conforme_ti_xmlschema_CanyType,
	conforme_ti_xmlschema_CanyURI,
	conforme_ti_xmlschema_Cbase64Binary,
	conforme_ti_xmlschema_Cboolean,
	conforme_ti_xmlschema_Cbyte,
	conforme_ti_xmlschema_Cdate,
	conforme_ti_xmlschema_CdateTime,
	conforme_ti_xmlschema_Cdecimal,
	conforme_ti_xmlschema_Cdouble,
	conforme_ti_xmlschema_Cduration,
	conforme_ti_xmlschema_Cfloat,
	conforme_ti_xmlschema_CgDay,
	conforme_ti_xmlschema_CgMonth,
	conforme_ti_xmlschema_CgMonthDay,
	conforme_ti_xmlschema_CgYear,
	conforme_ti_xmlschema_CgYearMonth,
	conforme_ti_xmlschema_ChexBinary,
	conforme_ti_xmlschema_Cint,
	conforme_ti_xmlschema_Cinteger,
	conforme_ti_xmlschema_Clanguage,
	conforme_ti_xmlschema_Clong,
	conforme_ti_xmlschema_CnegativeInteger,
	conforme_ti_xmlschema_CnonNegativeInteger,
	conforme_ti_xmlschema_CnonPositiveInteger,
	conforme_ti_xmlschema_CnormalizedString,
	conforme_ti_xmlschema_CpositiveInteger,
	conforme_ti_xmlschema_Cshort,
	conforme_ti_xmlschema_Cstring,
	conforme_ti_xmlschema_Ctime,
	conforme_ti_xmlschema_Ctoken,
	conforme_ti_xmlschema_CunsignedByte,
	conforme_ti_xmlschema_CunsignedInt,
	conforme_ti_xmlschema_CunsignedLong,
	conforme_ti_xmlschema_CunsignedShort,
	conforme_ti_xmlschema_CstringType,
	conforme_ti_xmlschema_CNCNameType,
	conforme_ti_xmlschema_CdateTimeType,
	conforme_ti_xmlschema_CanySimpleTypeType,
	conforme_ti_xmlschema_Cbase64BinaryType,
	conforme_ti_xmlschema_CintegerType,
	conforme_ti_xmlschema_last,


};

enum
{
	conforme_mi_oval_first_CCheckEnumeration,
	conforme_mi_oval_last_CCheckEnumeration = conforme_mi_oval_first_CCheckEnumeration,
};
enum
{
	conforme_mi_oval_first_CClassEnumeration = conforme_mi_oval_last_CCheckEnumeration,
	conforme_mi_oval_last_CClassEnumeration = conforme_mi_oval_first_CClassEnumeration,
};
enum
{
	conforme_mi_oval_first_CComplexDatatypeEnumeration = conforme_mi_oval_last_CClassEnumeration,
	conforme_mi_oval_last_CComplexDatatypeEnumeration = conforme_mi_oval_first_CComplexDatatypeEnumeration,
};
enum
{
	conforme_mi_oval_first_CDatatypeEnumeration = conforme_mi_oval_last_CComplexDatatypeEnumeration,
	conforme_mi_oval_last_CDatatypeEnumeration = conforme_mi_oval_first_CDatatypeEnumeration,
};
enum
{
	conforme_mi_oval_first_CDefinitionIDPattern = conforme_mi_oval_last_CDatatypeEnumeration,
	conforme_mi_oval_last_CDefinitionIDPattern = conforme_mi_oval_first_CDefinitionIDPattern,
};
enum
{
	conforme_mi_oval_first_CDeprecatedInfoType = conforme_mi_oval_last_CDefinitionIDPattern,
	conforme_mi_oval_CDeprecatedInfoType_version = conforme_mi_oval_first_CDeprecatedInfoType,
	conforme_mi_oval_CDeprecatedInfoType_reason,
	conforme_mi_oval_CDeprecatedInfoType_comment,
	conforme_mi_oval_last_CDeprecatedInfoType,
};
enum
{
	conforme_mi_oval_first_CElementMapItemType = conforme_mi_oval_last_CDeprecatedInfoType,
	conforme_mi_oval_CElementMapItemType_unnamed = conforme_mi_oval_first_CElementMapItemType,
	conforme_mi_oval_CElementMapItemType_target_namespace,
	conforme_mi_oval_last_CElementMapItemType,
};
enum
{
	conforme_mi_oval_first_CElementMapType = conforme_mi_oval_last_CElementMapItemType,
	conforme_mi_oval_CElementMapType_test = conforme_mi_oval_first_CElementMapType,
	conforme_mi_oval_CElementMapType_object,
	conforme_mi_oval_CElementMapType_state,
	conforme_mi_oval_CElementMapType_item,
	conforme_mi_oval_last_CElementMapType,
};
enum
{
	conforme_mi_oval_first_CEmptyStringType = conforme_mi_oval_last_CElementMapType,
	conforme_mi_oval_last_CEmptyStringType = conforme_mi_oval_first_CEmptyStringType,
};
enum
{
	conforme_mi_oval_first_CExistenceEnumeration = conforme_mi_oval_last_CEmptyStringType,
	conforme_mi_oval_last_CExistenceEnumeration = conforme_mi_oval_first_CExistenceEnumeration,
};
enum
{
	conforme_mi_oval_first_CFamilyEnumeration = conforme_mi_oval_last_CExistenceEnumeration,
	conforme_mi_oval_last_CFamilyEnumeration = conforme_mi_oval_first_CFamilyEnumeration,
};
enum
{
	conforme_mi_oval_first_CGeneratorType = conforme_mi_oval_last_CFamilyEnumeration,
	conforme_mi_oval_CGeneratorType_product_name = conforme_mi_oval_first_CGeneratorType,
	conforme_mi_oval_CGeneratorType_product_version,
	conforme_mi_oval_CGeneratorType_schema_version,
	conforme_mi_oval_CGeneratorType_timestamp,
	conforme_mi_oval_last_CGeneratorType,
};
enum
{
	conforme_mi_oval_first_CItemIDPattern = conforme_mi_oval_last_CGeneratorType,
	conforme_mi_oval_last_CItemIDPattern = conforme_mi_oval_first_CItemIDPattern,
};
enum
{
	conforme_mi_oval_first_CMessageLevelEnumeration = conforme_mi_oval_last_CItemIDPattern,
	conforme_mi_oval_last_CMessageLevelEnumeration = conforme_mi_oval_first_CMessageLevelEnumeration,
};
enum
{
	conforme_mi_oval_first_CMessageType = conforme_mi_oval_last_CMessageLevelEnumeration,
	conforme_mi_oval_CMessageType_unnamed = conforme_mi_oval_first_CMessageType,
	conforme_mi_oval_CMessageType_level,
	conforme_mi_oval_last_CMessageType,
};
enum
{
	conforme_mi_oval_first_CNonEmptyStringType = conforme_mi_oval_last_CMessageType,
	conforme_mi_oval_last_CNonEmptyStringType = conforme_mi_oval_first_CNonEmptyStringType,
};
enum
{
	conforme_mi_oval_first_CNotesType = conforme_mi_oval_last_CNonEmptyStringType,
	conforme_mi_oval_CNotesType_note = conforme_mi_oval_first_CNotesType,
	conforme_mi_oval_last_CNotesType,
};
enum
{
	conforme_mi_oval_first_CObjectIDPattern = conforme_mi_oval_last_CNotesType,
	conforme_mi_oval_last_CObjectIDPattern = conforme_mi_oval_first_CObjectIDPattern,
};
enum
{
	conforme_mi_oval_first_COperationEnumeration = conforme_mi_oval_last_CObjectIDPattern,
	conforme_mi_oval_last_COperationEnumeration = conforme_mi_oval_first_COperationEnumeration,
};
enum
{
	conforme_mi_oval_first_COperatorEnumeration = conforme_mi_oval_last_COperationEnumeration,
	conforme_mi_oval_last_COperatorEnumeration = conforme_mi_oval_first_COperatorEnumeration,
};
enum
{
	conforme_mi_oval_first_CSchemaVersionPattern = conforme_mi_oval_last_COperatorEnumeration,
	conforme_mi_oval_last_CSchemaVersionPattern = conforme_mi_oval_first_CSchemaVersionPattern,
};
enum
{
	conforme_mi_oval_first_CSchemaVersionType = conforme_mi_oval_last_CSchemaVersionPattern,
	conforme_mi_oval_CSchemaVersionType_unnamed = conforme_mi_oval_first_CSchemaVersionType,
	conforme_mi_oval_CSchemaVersionType_platform,
	conforme_mi_oval_last_CSchemaVersionType,
};
enum
{
	conforme_mi_oval_first_CSimpleDatatypeEnumeration = conforme_mi_oval_last_CSchemaVersionType,
	conforme_mi_oval_last_CSimpleDatatypeEnumeration = conforme_mi_oval_first_CSimpleDatatypeEnumeration,
};
enum
{
	conforme_mi_oval_first_CStateIDPattern = conforme_mi_oval_last_CSimpleDatatypeEnumeration,
	conforme_mi_oval_last_CStateIDPattern = conforme_mi_oval_first_CStateIDPattern,
};
enum
{
	conforme_mi_oval_first_CTestIDPattern = conforme_mi_oval_last_CStateIDPattern,
	conforme_mi_oval_last_CTestIDPattern = conforme_mi_oval_first_CTestIDPattern,
};
enum
{
	conforme_mi_oval_first_CVariableIDPattern = conforme_mi_oval_last_CTestIDPattern,
	conforme_mi_oval_last_CVariableIDPattern = conforme_mi_oval_first_CVariableIDPattern,
};
enum
{
	conforme_mi_oval_first_CStateIDPatternType = conforme_mi_oval_last_CVariableIDPattern,
	conforme_mi_oval_CStateIDPatternType_unnamed = conforme_mi_oval_first_CStateIDPatternType,
	conforme_mi_oval_last_CStateIDPatternType,
};
enum
{
	conforme_mi_oval_first_CObjectIDPatternType = conforme_mi_oval_last_CStateIDPatternType,
	conforme_mi_oval_CObjectIDPatternType_unnamed = conforme_mi_oval_first_CObjectIDPatternType,
	conforme_mi_oval_last_CObjectIDPatternType,
};
enum
{
	conforme_mi_oval_first_CversionType = conforme_mi_oval_last_CObjectIDPatternType,
	conforme_mi_oval_CversionType_unnamed = conforme_mi_oval_first_CversionType,
	conforme_mi_oval_last_CversionType,
};
enum
{
	conforme_mi_oval_first_CversionType2 = conforme_mi_oval_last_CversionType,
	conforme_mi_oval_last_CversionType2 = conforme_mi_oval_first_CversionType2,
};
enum
{
	conforme_mi_oval_first_CSchemaVersionPatternType = conforme_mi_oval_last_CversionType2,
	conforme_mi_oval_CSchemaVersionPatternType_unnamed = conforme_mi_oval_first_CSchemaVersionPatternType,
	conforme_mi_oval_last_CSchemaVersionPatternType,
};
enum
{
	conforme_mi_oval_def_first_CAffectedType = conforme_mi_oval_last_CSchemaVersionPatternType,
	conforme_mi_oval_def_CAffectedType_family = conforme_mi_oval_def_first_CAffectedType,
	conforme_mi_oval_def_CAffectedType_platform,
	conforme_mi_oval_def_CAffectedType_product,
	conforme_mi_oval_def_last_CAffectedType,
};
enum
{
	conforme_mi_oval_def_first_CArithmeticEnumeration = conforme_mi_oval_def_last_CAffectedType,
	conforme_mi_oval_def_last_CArithmeticEnumeration = conforme_mi_oval_def_first_CArithmeticEnumeration,
};
enum
{
	conforme_mi_oval_def_first_CArithmeticFunctionType = conforme_mi_oval_def_last_CArithmeticEnumeration,
	conforme_mi_oval_def_CArithmeticFunctionType_arithmetic_operation = conforme_mi_oval_def_first_CArithmeticFunctionType,
	conforme_mi_oval_def_CArithmeticFunctionType_object_component,
	conforme_mi_oval_def_CArithmeticFunctionType_variable_component,
	conforme_mi_oval_def_CArithmeticFunctionType_literal_component,
	conforme_mi_oval_def_CArithmeticFunctionType_arithmetic,
	conforme_mi_oval_def_CArithmeticFunctionType_begin,
	conforme_mi_oval_def_CArithmeticFunctionType_concat,
	conforme_mi_oval_def_CArithmeticFunctionType_end,
	conforme_mi_oval_def_CArithmeticFunctionType_escape_regex,
	conforme_mi_oval_def_CArithmeticFunctionType_split,
	conforme_mi_oval_def_CArithmeticFunctionType_substring,
	conforme_mi_oval_def_CArithmeticFunctionType_time_difference,
	conforme_mi_oval_def_CArithmeticFunctionType_regex_capture,
	conforme_mi_oval_def_CArithmeticFunctionType_unique,
	conforme_mi_oval_def_CArithmeticFunctionType_count,
	conforme_mi_oval_def_CArithmeticFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CArithmeticFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CBeginFunctionType = conforme_mi_oval_def_last_CArithmeticFunctionType,
	conforme_mi_oval_def_CBeginFunctionType_character = conforme_mi_oval_def_first_CBeginFunctionType,
	conforme_mi_oval_def_CBeginFunctionType_object_component,
	conforme_mi_oval_def_CBeginFunctionType_variable_component,
	conforme_mi_oval_def_CBeginFunctionType_literal_component,
	conforme_mi_oval_def_CBeginFunctionType_arithmetic,
	conforme_mi_oval_def_CBeginFunctionType_begin,
	conforme_mi_oval_def_CBeginFunctionType_concat,
	conforme_mi_oval_def_CBeginFunctionType_end,
	conforme_mi_oval_def_CBeginFunctionType_escape_regex,
	conforme_mi_oval_def_CBeginFunctionType_split,
	conforme_mi_oval_def_CBeginFunctionType_substring,
	conforme_mi_oval_def_CBeginFunctionType_time_difference,
	conforme_mi_oval_def_CBeginFunctionType_regex_capture,
	conforme_mi_oval_def_CBeginFunctionType_unique,
	conforme_mi_oval_def_CBeginFunctionType_count,
	conforme_mi_oval_def_CBeginFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CBeginFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CConcatFunctionType = conforme_mi_oval_def_last_CBeginFunctionType,
	conforme_mi_oval_def_CConcatFunctionType_object_component = conforme_mi_oval_def_first_CConcatFunctionType,
	conforme_mi_oval_def_CConcatFunctionType_variable_component,
	conforme_mi_oval_def_CConcatFunctionType_literal_component,
	conforme_mi_oval_def_CConcatFunctionType_arithmetic,
	conforme_mi_oval_def_CConcatFunctionType_begin,
	conforme_mi_oval_def_CConcatFunctionType_concat,
	conforme_mi_oval_def_CConcatFunctionType_end,
	conforme_mi_oval_def_CConcatFunctionType_escape_regex,
	conforme_mi_oval_def_CConcatFunctionType_split,
	conforme_mi_oval_def_CConcatFunctionType_substring,
	conforme_mi_oval_def_CConcatFunctionType_time_difference,
	conforme_mi_oval_def_CConcatFunctionType_regex_capture,
	conforme_mi_oval_def_CConcatFunctionType_unique,
	conforme_mi_oval_def_CConcatFunctionType_count,
	conforme_mi_oval_def_CConcatFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CConcatFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CCountFunctionType = conforme_mi_oval_def_last_CConcatFunctionType,
	conforme_mi_oval_def_CCountFunctionType_object_component = conforme_mi_oval_def_first_CCountFunctionType,
	conforme_mi_oval_def_CCountFunctionType_variable_component,
	conforme_mi_oval_def_CCountFunctionType_literal_component,
	conforme_mi_oval_def_CCountFunctionType_arithmetic,
	conforme_mi_oval_def_CCountFunctionType_begin,
	conforme_mi_oval_def_CCountFunctionType_concat,
	conforme_mi_oval_def_CCountFunctionType_end,
	conforme_mi_oval_def_CCountFunctionType_escape_regex,
	conforme_mi_oval_def_CCountFunctionType_split,
	conforme_mi_oval_def_CCountFunctionType_substring,
	conforme_mi_oval_def_CCountFunctionType_time_difference,
	conforme_mi_oval_def_CCountFunctionType_regex_capture,
	conforme_mi_oval_def_CCountFunctionType_unique,
	conforme_mi_oval_def_CCountFunctionType_count,
	conforme_mi_oval_def_CCountFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CCountFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CCriteriaType = conforme_mi_oval_def_last_CCountFunctionType,
	conforme_mi_oval_def_CCriteriaType_applicability_check = conforme_mi_oval_def_first_CCriteriaType,
	conforme_mi_oval_def_CCriteriaType_operator2,
	conforme_mi_oval_def_CCriteriaType_negate,
	conforme_mi_oval_def_CCriteriaType_comment,
	conforme_mi_oval_def_CCriteriaType_criteria,
	conforme_mi_oval_def_CCriteriaType_criterion,
	conforme_mi_oval_def_CCriteriaType_extend_definition,
	conforme_mi_oval_def_last_CCriteriaType,
};
enum
{
	conforme_mi_oval_def_first_CCriterionType = conforme_mi_oval_def_last_CCriteriaType,
	conforme_mi_oval_def_CCriterionType_applicability_check = conforme_mi_oval_def_first_CCriterionType,
	conforme_mi_oval_def_CCriterionType_test_ref,
	conforme_mi_oval_def_CCriterionType_negate,
	conforme_mi_oval_def_CCriterionType_comment,
	conforme_mi_oval_def_last_CCriterionType,
};
enum
{
	conforme_mi_oval_def_first_CDateTimeFormatEnumeration = conforme_mi_oval_def_last_CCriterionType,
	conforme_mi_oval_def_last_CDateTimeFormatEnumeration = conforme_mi_oval_def_first_CDateTimeFormatEnumeration,
};
enum
{
	conforme_mi_oval_def_first_CDefinitionType = conforme_mi_oval_def_last_CDateTimeFormatEnumeration,
	conforme_mi_oval_def_CDefinitionType_id = conforme_mi_oval_def_first_CDefinitionType,
	conforme_mi_oval_def_CDefinitionType_version,
	conforme_mi_oval_def_CDefinitionType_class2,
	conforme_mi_oval_def_CDefinitionType_deprecated,
	conforme_mi_oval_def_CDefinitionType_Signature,
	conforme_mi_oval_def_CDefinitionType_metadata,
	conforme_mi_oval_def_CDefinitionType_notes,
	conforme_mi_oval_def_CDefinitionType_notes2,
	conforme_mi_oval_def_CDefinitionType_criteria,
	conforme_mi_oval_def_last_CDefinitionType,
};
enum
{
	conforme_mi_oval_def_first_CDefinitionsType = conforme_mi_oval_def_last_CDefinitionType,
	conforme_mi_oval_def_CDefinitionsType_definition = conforme_mi_oval_def_first_CDefinitionsType,
	conforme_mi_oval_def_last_CDefinitionsType,
};
enum
{
	conforme_mi_oval_def_first_CEndFunctionType = conforme_mi_oval_def_last_CDefinitionsType,
	conforme_mi_oval_def_CEndFunctionType_character = conforme_mi_oval_def_first_CEndFunctionType,
	conforme_mi_oval_def_CEndFunctionType_object_component,
	conforme_mi_oval_def_CEndFunctionType_variable_component,
	conforme_mi_oval_def_CEndFunctionType_literal_component,
	conforme_mi_oval_def_CEndFunctionType_arithmetic,
	conforme_mi_oval_def_CEndFunctionType_begin,
	conforme_mi_oval_def_CEndFunctionType_concat,
	conforme_mi_oval_def_CEndFunctionType_end,
	conforme_mi_oval_def_CEndFunctionType_escape_regex,
	conforme_mi_oval_def_CEndFunctionType_split,
	conforme_mi_oval_def_CEndFunctionType_substring,
	conforme_mi_oval_def_CEndFunctionType_time_difference,
	conforme_mi_oval_def_CEndFunctionType_regex_capture,
	conforme_mi_oval_def_CEndFunctionType_unique,
	conforme_mi_oval_def_CEndFunctionType_count,
	conforme_mi_oval_def_CEndFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CEndFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CEntityComplexBaseType = conforme_mi_oval_def_last_CEndFunctionType,
	conforme_mi_oval_def_CEntityComplexBaseType_datatype = conforme_mi_oval_def_first_CEntityComplexBaseType,
	conforme_mi_oval_def_CEntityComplexBaseType_operation,
	conforme_mi_oval_def_CEntityComplexBaseType_mask,
	conforme_mi_oval_def_CEntityComplexBaseType_var_ref,
	conforme_mi_oval_def_CEntityComplexBaseType_var_check,
	conforme_mi_oval_def_last_CEntityComplexBaseType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectAnySimpleType = conforme_mi_oval_def_last_CEntityComplexBaseType,
	conforme_mi_oval_def_CEntityObjectAnySimpleType_operation = conforme_mi_oval_def_first_CEntityObjectAnySimpleType,
	conforme_mi_oval_def_CEntityObjectAnySimpleType_mask,
	conforme_mi_oval_def_CEntityObjectAnySimpleType_var_ref,
	conforme_mi_oval_def_CEntityObjectAnySimpleType_var_check,
	conforme_mi_oval_def_CEntityObjectAnySimpleType_datatype,
	conforme_mi_oval_def_CEntityObjectAnySimpleType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectAnySimpleType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectBinaryType = conforme_mi_oval_def_last_CEntityObjectAnySimpleType,
	conforme_mi_oval_def_CEntityObjectBinaryType_operation = conforme_mi_oval_def_first_CEntityObjectBinaryType,
	conforme_mi_oval_def_CEntityObjectBinaryType_mask,
	conforme_mi_oval_def_CEntityObjectBinaryType_var_ref,
	conforme_mi_oval_def_CEntityObjectBinaryType_var_check,
	conforme_mi_oval_def_CEntityObjectBinaryType_datatype,
	conforme_mi_oval_def_CEntityObjectBinaryType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectBinaryType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectBoolType = conforme_mi_oval_def_last_CEntityObjectBinaryType,
	conforme_mi_oval_def_CEntityObjectBoolType_operation = conforme_mi_oval_def_first_CEntityObjectBoolType,
	conforme_mi_oval_def_CEntityObjectBoolType_mask,
	conforme_mi_oval_def_CEntityObjectBoolType_var_ref,
	conforme_mi_oval_def_CEntityObjectBoolType_var_check,
	conforme_mi_oval_def_CEntityObjectBoolType_datatype,
	conforme_mi_oval_def_CEntityObjectBoolType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectBoolType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectFieldType = conforme_mi_oval_def_last_CEntityObjectBoolType,
	conforme_mi_oval_def_CEntityObjectFieldType_unnamed = conforme_mi_oval_def_first_CEntityObjectFieldType,
	conforme_mi_oval_def_CEntityObjectFieldType_name,
	conforme_mi_oval_def_CEntityObjectFieldType_datatype,
	conforme_mi_oval_def_CEntityObjectFieldType_operation,
	conforme_mi_oval_def_CEntityObjectFieldType_mask,
	conforme_mi_oval_def_CEntityObjectFieldType_var_ref,
	conforme_mi_oval_def_CEntityObjectFieldType_var_check,
	conforme_mi_oval_def_CEntityObjectFieldType_entity_check,
	conforme_mi_oval_def_last_CEntityObjectFieldType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectFloatType = conforme_mi_oval_def_last_CEntityObjectFieldType,
	conforme_mi_oval_def_CEntityObjectFloatType_operation = conforme_mi_oval_def_first_CEntityObjectFloatType,
	conforme_mi_oval_def_CEntityObjectFloatType_mask,
	conforme_mi_oval_def_CEntityObjectFloatType_var_ref,
	conforme_mi_oval_def_CEntityObjectFloatType_var_check,
	conforme_mi_oval_def_CEntityObjectFloatType_datatype,
	conforme_mi_oval_def_CEntityObjectFloatType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectFloatType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectIPAddressStringType = conforme_mi_oval_def_last_CEntityObjectFloatType,
	conforme_mi_oval_def_CEntityObjectIPAddressStringType_operation = conforme_mi_oval_def_first_CEntityObjectIPAddressStringType,
	conforme_mi_oval_def_CEntityObjectIPAddressStringType_mask,
	conforme_mi_oval_def_CEntityObjectIPAddressStringType_var_ref,
	conforme_mi_oval_def_CEntityObjectIPAddressStringType_var_check,
	conforme_mi_oval_def_CEntityObjectIPAddressStringType_datatype,
	conforme_mi_oval_def_CEntityObjectIPAddressStringType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectIPAddressStringType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectIPAddressType = conforme_mi_oval_def_last_CEntityObjectIPAddressStringType,
	conforme_mi_oval_def_CEntityObjectIPAddressType_operation = conforme_mi_oval_def_first_CEntityObjectIPAddressType,
	conforme_mi_oval_def_CEntityObjectIPAddressType_mask,
	conforme_mi_oval_def_CEntityObjectIPAddressType_var_ref,
	conforme_mi_oval_def_CEntityObjectIPAddressType_var_check,
	conforme_mi_oval_def_CEntityObjectIPAddressType_datatype,
	conforme_mi_oval_def_CEntityObjectIPAddressType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectIPAddressType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectIntType = conforme_mi_oval_def_last_CEntityObjectIPAddressType,
	conforme_mi_oval_def_CEntityObjectIntType_operation = conforme_mi_oval_def_first_CEntityObjectIntType,
	conforme_mi_oval_def_CEntityObjectIntType_mask,
	conforme_mi_oval_def_CEntityObjectIntType_var_ref,
	conforme_mi_oval_def_CEntityObjectIntType_var_check,
	conforme_mi_oval_def_CEntityObjectIntType_datatype,
	conforme_mi_oval_def_CEntityObjectIntType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectIntType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectRecordType = conforme_mi_oval_def_last_CEntityObjectIntType,
	conforme_mi_oval_def_CEntityObjectRecordType_datatype = conforme_mi_oval_def_first_CEntityObjectRecordType,
	conforme_mi_oval_def_CEntityObjectRecordType_operation,
	conforme_mi_oval_def_CEntityObjectRecordType_mask,
	conforme_mi_oval_def_CEntityObjectRecordType_var_ref,
	conforme_mi_oval_def_CEntityObjectRecordType_var_check,
	conforme_mi_oval_def_CEntityObjectRecordType_field,
	conforme_mi_oval_def_last_CEntityObjectRecordType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectStringType = conforme_mi_oval_def_last_CEntityObjectRecordType,
	conforme_mi_oval_def_CEntityObjectStringType_operation = conforme_mi_oval_def_first_CEntityObjectStringType,
	conforme_mi_oval_def_CEntityObjectStringType_mask,
	conforme_mi_oval_def_CEntityObjectStringType_var_ref,
	conforme_mi_oval_def_CEntityObjectStringType_var_check,
	conforme_mi_oval_def_CEntityObjectStringType_datatype,
	conforme_mi_oval_def_CEntityObjectStringType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectStringType,
};
enum
{
	conforme_mi_oval_def_first_CEntityObjectVersionType = conforme_mi_oval_def_last_CEntityObjectStringType,
	conforme_mi_oval_def_CEntityObjectVersionType_operation = conforme_mi_oval_def_first_CEntityObjectVersionType,
	conforme_mi_oval_def_CEntityObjectVersionType_mask,
	conforme_mi_oval_def_CEntityObjectVersionType_var_ref,
	conforme_mi_oval_def_CEntityObjectVersionType_var_check,
	conforme_mi_oval_def_CEntityObjectVersionType_datatype,
	conforme_mi_oval_def_CEntityObjectVersionType_unnamed,
	conforme_mi_oval_def_last_CEntityObjectVersionType,
};
enum
{
	conforme_mi_oval_def_first_CEntitySimpleBaseType = conforme_mi_oval_def_last_CEntityObjectVersionType,
	conforme_mi_oval_def_CEntitySimpleBaseType_unnamed = conforme_mi_oval_def_first_CEntitySimpleBaseType,
	conforme_mi_oval_def_CEntitySimpleBaseType_datatype,
	conforme_mi_oval_def_CEntitySimpleBaseType_operation,
	conforme_mi_oval_def_CEntitySimpleBaseType_mask,
	conforme_mi_oval_def_CEntitySimpleBaseType_var_ref,
	conforme_mi_oval_def_CEntitySimpleBaseType_var_check,
	conforme_mi_oval_def_last_CEntitySimpleBaseType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateAnySimpleType = conforme_mi_oval_def_last_CEntitySimpleBaseType,
	conforme_mi_oval_def_CEntityStateAnySimpleType_operation = conforme_mi_oval_def_first_CEntityStateAnySimpleType,
	conforme_mi_oval_def_CEntityStateAnySimpleType_mask,
	conforme_mi_oval_def_CEntityStateAnySimpleType_var_ref,
	conforme_mi_oval_def_CEntityStateAnySimpleType_var_check,
	conforme_mi_oval_def_CEntityStateAnySimpleType_entity_check,
	conforme_mi_oval_def_CEntityStateAnySimpleType_check_existence,
	conforme_mi_oval_def_CEntityStateAnySimpleType_datatype,
	conforme_mi_oval_def_CEntityStateAnySimpleType_unnamed,
	conforme_mi_oval_def_last_CEntityStateAnySimpleType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateBinaryType = conforme_mi_oval_def_last_CEntityStateAnySimpleType,
	conforme_mi_oval_def_CEntityStateBinaryType_operation = conforme_mi_oval_def_first_CEntityStateBinaryType,
	conforme_mi_oval_def_CEntityStateBinaryType_mask,
	conforme_mi_oval_def_CEntityStateBinaryType_var_ref,
	conforme_mi_oval_def_CEntityStateBinaryType_var_check,
	conforme_mi_oval_def_CEntityStateBinaryType_entity_check,
	conforme_mi_oval_def_CEntityStateBinaryType_check_existence,
	conforme_mi_oval_def_CEntityStateBinaryType_datatype,
	conforme_mi_oval_def_CEntityStateBinaryType_unnamed,
	conforme_mi_oval_def_last_CEntityStateBinaryType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateBoolType = conforme_mi_oval_def_last_CEntityStateBinaryType,
	conforme_mi_oval_def_CEntityStateBoolType_operation = conforme_mi_oval_def_first_CEntityStateBoolType,
	conforme_mi_oval_def_CEntityStateBoolType_mask,
	conforme_mi_oval_def_CEntityStateBoolType_var_ref,
	conforme_mi_oval_def_CEntityStateBoolType_var_check,
	conforme_mi_oval_def_CEntityStateBoolType_entity_check,
	conforme_mi_oval_def_CEntityStateBoolType_check_existence,
	conforme_mi_oval_def_CEntityStateBoolType_datatype,
	conforme_mi_oval_def_CEntityStateBoolType_unnamed,
	conforme_mi_oval_def_last_CEntityStateBoolType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateComplexBaseType = conforme_mi_oval_def_last_CEntityStateBoolType,
	conforme_mi_oval_def_CEntityStateComplexBaseType_datatype = conforme_mi_oval_def_first_CEntityStateComplexBaseType,
	conforme_mi_oval_def_CEntityStateComplexBaseType_operation,
	conforme_mi_oval_def_CEntityStateComplexBaseType_mask,
	conforme_mi_oval_def_CEntityStateComplexBaseType_var_ref,
	conforme_mi_oval_def_CEntityStateComplexBaseType_var_check,
	conforme_mi_oval_def_CEntityStateComplexBaseType_entity_check,
	conforme_mi_oval_def_CEntityStateComplexBaseType_check_existence,
	conforme_mi_oval_def_last_CEntityStateComplexBaseType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateDebianEVRStringType = conforme_mi_oval_def_last_CEntityStateComplexBaseType,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_operation = conforme_mi_oval_def_first_CEntityStateDebianEVRStringType,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_mask,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_var_ref,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_var_check,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_entity_check,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_check_existence,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_datatype,
	conforme_mi_oval_def_CEntityStateDebianEVRStringType_unnamed,
	conforme_mi_oval_def_last_CEntityStateDebianEVRStringType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateEVRStringType = conforme_mi_oval_def_last_CEntityStateDebianEVRStringType,
	conforme_mi_oval_def_CEntityStateEVRStringType_operation = conforme_mi_oval_def_first_CEntityStateEVRStringType,
	conforme_mi_oval_def_CEntityStateEVRStringType_mask,
	conforme_mi_oval_def_CEntityStateEVRStringType_var_ref,
	conforme_mi_oval_def_CEntityStateEVRStringType_var_check,
	conforme_mi_oval_def_CEntityStateEVRStringType_entity_check,
	conforme_mi_oval_def_CEntityStateEVRStringType_check_existence,
	conforme_mi_oval_def_CEntityStateEVRStringType_datatype,
	conforme_mi_oval_def_CEntityStateEVRStringType_unnamed,
	conforme_mi_oval_def_last_CEntityStateEVRStringType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateFieldType = conforme_mi_oval_def_last_CEntityStateEVRStringType,
	conforme_mi_oval_def_CEntityStateFieldType_unnamed = conforme_mi_oval_def_first_CEntityStateFieldType,
	conforme_mi_oval_def_CEntityStateFieldType_name,
	conforme_mi_oval_def_CEntityStateFieldType_datatype,
	conforme_mi_oval_def_CEntityStateFieldType_operation,
	conforme_mi_oval_def_CEntityStateFieldType_mask,
	conforme_mi_oval_def_CEntityStateFieldType_var_ref,
	conforme_mi_oval_def_CEntityStateFieldType_var_check,
	conforme_mi_oval_def_CEntityStateFieldType_entity_check,
	conforme_mi_oval_def_last_CEntityStateFieldType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateFileSetRevisionType = conforme_mi_oval_def_last_CEntityStateFieldType,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_operation = conforme_mi_oval_def_first_CEntityStateFileSetRevisionType,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_mask,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_var_ref,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_var_check,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_entity_check,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_check_existence,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_datatype,
	conforme_mi_oval_def_CEntityStateFileSetRevisionType_unnamed,
	conforme_mi_oval_def_last_CEntityStateFileSetRevisionType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateFloatType = conforme_mi_oval_def_last_CEntityStateFileSetRevisionType,
	conforme_mi_oval_def_CEntityStateFloatType_operation = conforme_mi_oval_def_first_CEntityStateFloatType,
	conforme_mi_oval_def_CEntityStateFloatType_mask,
	conforme_mi_oval_def_CEntityStateFloatType_var_ref,
	conforme_mi_oval_def_CEntityStateFloatType_var_check,
	conforme_mi_oval_def_CEntityStateFloatType_entity_check,
	conforme_mi_oval_def_CEntityStateFloatType_check_existence,
	conforme_mi_oval_def_CEntityStateFloatType_datatype,
	conforme_mi_oval_def_CEntityStateFloatType_unnamed,
	conforme_mi_oval_def_last_CEntityStateFloatType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateIOSVersionType = conforme_mi_oval_def_last_CEntityStateFloatType,
	conforme_mi_oval_def_CEntityStateIOSVersionType_operation = conforme_mi_oval_def_first_CEntityStateIOSVersionType,
	conforme_mi_oval_def_CEntityStateIOSVersionType_mask,
	conforme_mi_oval_def_CEntityStateIOSVersionType_var_ref,
	conforme_mi_oval_def_CEntityStateIOSVersionType_var_check,
	conforme_mi_oval_def_CEntityStateIOSVersionType_entity_check,
	conforme_mi_oval_def_CEntityStateIOSVersionType_check_existence,
	conforme_mi_oval_def_CEntityStateIOSVersionType_datatype,
	conforme_mi_oval_def_CEntityStateIOSVersionType_unnamed,
	conforme_mi_oval_def_last_CEntityStateIOSVersionType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateIPAddressStringType = conforme_mi_oval_def_last_CEntityStateIOSVersionType,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_operation = conforme_mi_oval_def_first_CEntityStateIPAddressStringType,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_mask,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_var_ref,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_var_check,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_entity_check,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_check_existence,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_datatype,
	conforme_mi_oval_def_CEntityStateIPAddressStringType_unnamed,
	conforme_mi_oval_def_last_CEntityStateIPAddressStringType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateIPAddressType = conforme_mi_oval_def_last_CEntityStateIPAddressStringType,
	conforme_mi_oval_def_CEntityStateIPAddressType_operation = conforme_mi_oval_def_first_CEntityStateIPAddressType,
	conforme_mi_oval_def_CEntityStateIPAddressType_mask,
	conforme_mi_oval_def_CEntityStateIPAddressType_var_ref,
	conforme_mi_oval_def_CEntityStateIPAddressType_var_check,
	conforme_mi_oval_def_CEntityStateIPAddressType_entity_check,
	conforme_mi_oval_def_CEntityStateIPAddressType_check_existence,
	conforme_mi_oval_def_CEntityStateIPAddressType_datatype,
	conforme_mi_oval_def_CEntityStateIPAddressType_unnamed,
	conforme_mi_oval_def_last_CEntityStateIPAddressType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateIntType = conforme_mi_oval_def_last_CEntityStateIPAddressType,
	conforme_mi_oval_def_CEntityStateIntType_operation = conforme_mi_oval_def_first_CEntityStateIntType,
	conforme_mi_oval_def_CEntityStateIntType_mask,
	conforme_mi_oval_def_CEntityStateIntType_var_ref,
	conforme_mi_oval_def_CEntityStateIntType_var_check,
	conforme_mi_oval_def_CEntityStateIntType_entity_check,
	conforme_mi_oval_def_CEntityStateIntType_check_existence,
	conforme_mi_oval_def_CEntityStateIntType_datatype,
	conforme_mi_oval_def_CEntityStateIntType_unnamed,
	conforme_mi_oval_def_last_CEntityStateIntType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateRecordType = conforme_mi_oval_def_last_CEntityStateIntType,
	conforme_mi_oval_def_CEntityStateRecordType_datatype = conforme_mi_oval_def_first_CEntityStateRecordType,
	conforme_mi_oval_def_CEntityStateRecordType_operation,
	conforme_mi_oval_def_CEntityStateRecordType_mask,
	conforme_mi_oval_def_CEntityStateRecordType_var_ref,
	conforme_mi_oval_def_CEntityStateRecordType_var_check,
	conforme_mi_oval_def_CEntityStateRecordType_entity_check,
	conforme_mi_oval_def_CEntityStateRecordType_check_existence,
	conforme_mi_oval_def_CEntityStateRecordType_field,
	conforme_mi_oval_def_last_CEntityStateRecordType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateSimpleBaseType = conforme_mi_oval_def_last_CEntityStateRecordType,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_unnamed = conforme_mi_oval_def_first_CEntityStateSimpleBaseType,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_datatype,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_operation,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_mask,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_var_ref,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_var_check,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_entity_check,
	conforme_mi_oval_def_CEntityStateSimpleBaseType_check_existence,
	conforme_mi_oval_def_last_CEntityStateSimpleBaseType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateStringType = conforme_mi_oval_def_last_CEntityStateSimpleBaseType,
	conforme_mi_oval_def_CEntityStateStringType_operation = conforme_mi_oval_def_first_CEntityStateStringType,
	conforme_mi_oval_def_CEntityStateStringType_mask,
	conforme_mi_oval_def_CEntityStateStringType_var_ref,
	conforme_mi_oval_def_CEntityStateStringType_var_check,
	conforme_mi_oval_def_CEntityStateStringType_entity_check,
	conforme_mi_oval_def_CEntityStateStringType_check_existence,
	conforme_mi_oval_def_CEntityStateStringType_datatype,
	conforme_mi_oval_def_CEntityStateStringType_unnamed,
	conforme_mi_oval_def_last_CEntityStateStringType,
};
enum
{
	conforme_mi_oval_def_first_CEntityStateVersionType = conforme_mi_oval_def_last_CEntityStateStringType,
	conforme_mi_oval_def_CEntityStateVersionType_operation = conforme_mi_oval_def_first_CEntityStateVersionType,
	conforme_mi_oval_def_CEntityStateVersionType_mask,
	conforme_mi_oval_def_CEntityStateVersionType_var_ref,
	conforme_mi_oval_def_CEntityStateVersionType_var_check,
	conforme_mi_oval_def_CEntityStateVersionType_entity_check,
	conforme_mi_oval_def_CEntityStateVersionType_check_existence,
	conforme_mi_oval_def_CEntityStateVersionType_datatype,
	conforme_mi_oval_def_CEntityStateVersionType_unnamed,
	conforme_mi_oval_def_last_CEntityStateVersionType,
};
enum
{
	conforme_mi_oval_def_first_CEscapeRegexFunctionType = conforme_mi_oval_def_last_CEntityStateVersionType,
	conforme_mi_oval_def_CEscapeRegexFunctionType_object_component = conforme_mi_oval_def_first_CEscapeRegexFunctionType,
	conforme_mi_oval_def_CEscapeRegexFunctionType_variable_component,
	conforme_mi_oval_def_CEscapeRegexFunctionType_literal_component,
	conforme_mi_oval_def_CEscapeRegexFunctionType_arithmetic,
	conforme_mi_oval_def_CEscapeRegexFunctionType_begin,
	conforme_mi_oval_def_CEscapeRegexFunctionType_concat,
	conforme_mi_oval_def_CEscapeRegexFunctionType_end,
	conforme_mi_oval_def_CEscapeRegexFunctionType_escape_regex,
	conforme_mi_oval_def_CEscapeRegexFunctionType_split,
	conforme_mi_oval_def_CEscapeRegexFunctionType_substring,
	conforme_mi_oval_def_CEscapeRegexFunctionType_time_difference,
	conforme_mi_oval_def_CEscapeRegexFunctionType_regex_capture,
	conforme_mi_oval_def_CEscapeRegexFunctionType_unique,
	conforme_mi_oval_def_CEscapeRegexFunctionType_count,
	conforme_mi_oval_def_CEscapeRegexFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CEscapeRegexFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CExtendDefinitionType = conforme_mi_oval_def_last_CEscapeRegexFunctionType,
	conforme_mi_oval_def_CExtendDefinitionType_applicability_check = conforme_mi_oval_def_first_CExtendDefinitionType,
	conforme_mi_oval_def_CExtendDefinitionType_definition_ref,
	conforme_mi_oval_def_CExtendDefinitionType_negate,
	conforme_mi_oval_def_CExtendDefinitionType_comment,
	conforme_mi_oval_def_last_CExtendDefinitionType,
};
enum
{
	conforme_mi_oval_def_first_CFilterActionEnumeration = conforme_mi_oval_def_last_CExtendDefinitionType,
	conforme_mi_oval_def_last_CFilterActionEnumeration = conforme_mi_oval_def_first_CFilterActionEnumeration,
};
enum
{
	conforme_mi_oval_def_first_CGlobToRegexFunctionType = conforme_mi_oval_def_last_CFilterActionEnumeration,
	conforme_mi_oval_def_CGlobToRegexFunctionType_glob_noescape = conforme_mi_oval_def_first_CGlobToRegexFunctionType,
	conforme_mi_oval_def_CGlobToRegexFunctionType_object_component,
	conforme_mi_oval_def_CGlobToRegexFunctionType_variable_component,
	conforme_mi_oval_def_CGlobToRegexFunctionType_literal_component,
	conforme_mi_oval_def_CGlobToRegexFunctionType_arithmetic,
	conforme_mi_oval_def_CGlobToRegexFunctionType_begin,
	conforme_mi_oval_def_CGlobToRegexFunctionType_concat,
	conforme_mi_oval_def_CGlobToRegexFunctionType_end,
	conforme_mi_oval_def_CGlobToRegexFunctionType_escape_regex,
	conforme_mi_oval_def_CGlobToRegexFunctionType_split,
	conforme_mi_oval_def_CGlobToRegexFunctionType_substring,
	conforme_mi_oval_def_CGlobToRegexFunctionType_time_difference,
	conforme_mi_oval_def_CGlobToRegexFunctionType_regex_capture,
	conforme_mi_oval_def_CGlobToRegexFunctionType_unique,
	conforme_mi_oval_def_CGlobToRegexFunctionType_count,
	conforme_mi_oval_def_CGlobToRegexFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CGlobToRegexFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CLiteralComponentType = conforme_mi_oval_def_last_CGlobToRegexFunctionType,
	conforme_mi_oval_def_CLiteralComponentType_unnamed = conforme_mi_oval_def_first_CLiteralComponentType,
	conforme_mi_oval_def_CLiteralComponentType_datatype,
	conforme_mi_oval_def_last_CLiteralComponentType,
};
enum
{
	conforme_mi_oval_def_first_CMetadataType = conforme_mi_oval_def_last_CLiteralComponentType,
	conforme_mi_oval_def_CMetadataType_title = conforme_mi_oval_def_first_CMetadataType,
	conforme_mi_oval_def_CMetadataType_affected,
	conforme_mi_oval_def_CMetadataType_reference,
	conforme_mi_oval_def_CMetadataType_description,
	conforme_mi_oval_def_last_CMetadataType,
};
enum
{
	conforme_mi_oval_def_first_CObjectComponentType = conforme_mi_oval_def_last_CMetadataType,
	conforme_mi_oval_def_CObjectComponentType_object_ref = conforme_mi_oval_def_first_CObjectComponentType,
	conforme_mi_oval_def_CObjectComponentType_item_field,
	conforme_mi_oval_def_CObjectComponentType_record_field,
	conforme_mi_oval_def_last_CObjectComponentType,
};
enum
{
	conforme_mi_oval_def_first_CObjectRefType = conforme_mi_oval_def_last_CObjectComponentType,
	conforme_mi_oval_def_CObjectRefType_object_ref = conforme_mi_oval_def_first_CObjectRefType,
	conforme_mi_oval_def_last_CObjectRefType,
};
enum
{
	conforme_mi_oval_def_first_CObjectType = conforme_mi_oval_def_last_CObjectRefType,
	conforme_mi_oval_def_CObjectType_id = conforme_mi_oval_def_first_CObjectType,
	conforme_mi_oval_def_CObjectType_version,
	conforme_mi_oval_def_CObjectType_comment,
	conforme_mi_oval_def_CObjectType_deprecated,
	conforme_mi_oval_def_CObjectType_Signature,
	conforme_mi_oval_def_CObjectType_notes,
	conforme_mi_oval_def_CObjectType_notes2,
	conforme_mi_oval_def_last_CObjectType,
};
enum
{
	conforme_mi_oval_def_first_CObjectsType = conforme_mi_oval_def_last_CObjectType,
	conforme_mi_oval_def_last_CObjectsType = conforme_mi_oval_def_first_CObjectsType,
};
enum
{
	conforme_mi_oval_def_first_CPossibleRestrictionType = conforme_mi_oval_def_last_CObjectsType,
	conforme_mi_oval_def_CPossibleRestrictionType_operator2 = conforme_mi_oval_def_first_CPossibleRestrictionType,
	conforme_mi_oval_def_CPossibleRestrictionType_hint,
	conforme_mi_oval_def_CPossibleRestrictionType_restriction,
	conforme_mi_oval_def_last_CPossibleRestrictionType,
};
enum
{
	conforme_mi_oval_def_first_CPossibleValueType = conforme_mi_oval_def_last_CPossibleRestrictionType,
	conforme_mi_oval_def_CPossibleValueType_unnamed = conforme_mi_oval_def_first_CPossibleValueType,
	conforme_mi_oval_def_CPossibleValueType_hint,
	conforme_mi_oval_def_last_CPossibleValueType,
};
enum
{
	conforme_mi_oval_def_first_CReferenceType = conforme_mi_oval_def_last_CPossibleValueType,
	conforme_mi_oval_def_CReferenceType_source = conforme_mi_oval_def_first_CReferenceType,
	conforme_mi_oval_def_CReferenceType_ref_id,
	conforme_mi_oval_def_CReferenceType_ref_url,
	conforme_mi_oval_def_last_CReferenceType,
};
enum
{
	conforme_mi_oval_def_first_CRegexCaptureFunctionType = conforme_mi_oval_def_last_CReferenceType,
	conforme_mi_oval_def_CRegexCaptureFunctionType_pattern = conforme_mi_oval_def_first_CRegexCaptureFunctionType,
	conforme_mi_oval_def_CRegexCaptureFunctionType_object_component,
	conforme_mi_oval_def_CRegexCaptureFunctionType_variable_component,
	conforme_mi_oval_def_CRegexCaptureFunctionType_literal_component,
	conforme_mi_oval_def_CRegexCaptureFunctionType_arithmetic,
	conforme_mi_oval_def_CRegexCaptureFunctionType_begin,
	conforme_mi_oval_def_CRegexCaptureFunctionType_concat,
	conforme_mi_oval_def_CRegexCaptureFunctionType_end,
	conforme_mi_oval_def_CRegexCaptureFunctionType_escape_regex,
	conforme_mi_oval_def_CRegexCaptureFunctionType_split,
	conforme_mi_oval_def_CRegexCaptureFunctionType_substring,
	conforme_mi_oval_def_CRegexCaptureFunctionType_time_difference,
	conforme_mi_oval_def_CRegexCaptureFunctionType_regex_capture,
	conforme_mi_oval_def_CRegexCaptureFunctionType_unique,
	conforme_mi_oval_def_CRegexCaptureFunctionType_count,
	conforme_mi_oval_def_CRegexCaptureFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CRegexCaptureFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CRestrictionType = conforme_mi_oval_def_last_CRegexCaptureFunctionType,
	conforme_mi_oval_def_CRestrictionType_unnamed = conforme_mi_oval_def_first_CRestrictionType,
	conforme_mi_oval_def_CRestrictionType_operation,
	conforme_mi_oval_def_last_CRestrictionType,
};
enum
{
	conforme_mi_oval_def_first_CSetOperatorEnumeration = conforme_mi_oval_def_last_CRestrictionType,
	conforme_mi_oval_def_last_CSetOperatorEnumeration = conforme_mi_oval_def_first_CSetOperatorEnumeration,
};
enum
{
	conforme_mi_oval_def_first_CSplitFunctionType = conforme_mi_oval_def_last_CSetOperatorEnumeration,
	conforme_mi_oval_def_CSplitFunctionType_delimiter = conforme_mi_oval_def_first_CSplitFunctionType,
	conforme_mi_oval_def_CSplitFunctionType_object_component,
	conforme_mi_oval_def_CSplitFunctionType_variable_component,
	conforme_mi_oval_def_CSplitFunctionType_literal_component,
	conforme_mi_oval_def_CSplitFunctionType_arithmetic,
	conforme_mi_oval_def_CSplitFunctionType_begin,
	conforme_mi_oval_def_CSplitFunctionType_concat,
	conforme_mi_oval_def_CSplitFunctionType_end,
	conforme_mi_oval_def_CSplitFunctionType_escape_regex,
	conforme_mi_oval_def_CSplitFunctionType_split,
	conforme_mi_oval_def_CSplitFunctionType_substring,
	conforme_mi_oval_def_CSplitFunctionType_time_difference,
	conforme_mi_oval_def_CSplitFunctionType_regex_capture,
	conforme_mi_oval_def_CSplitFunctionType_unique,
	conforme_mi_oval_def_CSplitFunctionType_count,
	conforme_mi_oval_def_CSplitFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CSplitFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CStateRefType = conforme_mi_oval_def_last_CSplitFunctionType,
	conforme_mi_oval_def_CStateRefType_state_ref = conforme_mi_oval_def_first_CStateRefType,
	conforme_mi_oval_def_last_CStateRefType,
};
enum
{
	conforme_mi_oval_def_first_CStateType = conforme_mi_oval_def_last_CStateRefType,
	conforme_mi_oval_def_CStateType_id = conforme_mi_oval_def_first_CStateType,
	conforme_mi_oval_def_CStateType_version,
	conforme_mi_oval_def_CStateType_operator2,
	conforme_mi_oval_def_CStateType_comment,
	conforme_mi_oval_def_CStateType_deprecated,
	conforme_mi_oval_def_CStateType_Signature,
	conforme_mi_oval_def_CStateType_notes,
	conforme_mi_oval_def_CStateType_notes2,
	conforme_mi_oval_def_last_CStateType,
};
enum
{
	conforme_mi_oval_def_first_CStatesType = conforme_mi_oval_def_last_CStateType,
	conforme_mi_oval_def_last_CStatesType = conforme_mi_oval_def_first_CStatesType,
};
enum
{
	conforme_mi_oval_def_first_CSubstringFunctionType = conforme_mi_oval_def_last_CStatesType,
	conforme_mi_oval_def_CSubstringFunctionType_substring_start = conforme_mi_oval_def_first_CSubstringFunctionType,
	conforme_mi_oval_def_CSubstringFunctionType_substring_length,
	conforme_mi_oval_def_CSubstringFunctionType_object_component,
	conforme_mi_oval_def_CSubstringFunctionType_variable_component,
	conforme_mi_oval_def_CSubstringFunctionType_literal_component,
	conforme_mi_oval_def_CSubstringFunctionType_arithmetic,
	conforme_mi_oval_def_CSubstringFunctionType_begin,
	conforme_mi_oval_def_CSubstringFunctionType_concat,
	conforme_mi_oval_def_CSubstringFunctionType_end,
	conforme_mi_oval_def_CSubstringFunctionType_escape_regex,
	conforme_mi_oval_def_CSubstringFunctionType_split,
	conforme_mi_oval_def_CSubstringFunctionType_substring,
	conforme_mi_oval_def_CSubstringFunctionType_time_difference,
	conforme_mi_oval_def_CSubstringFunctionType_regex_capture,
	conforme_mi_oval_def_CSubstringFunctionType_unique,
	conforme_mi_oval_def_CSubstringFunctionType_count,
	conforme_mi_oval_def_CSubstringFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CSubstringFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CTestType = conforme_mi_oval_def_last_CSubstringFunctionType,
	conforme_mi_oval_def_CTestType_id = conforme_mi_oval_def_first_CTestType,
	conforme_mi_oval_def_CTestType_version,
	conforme_mi_oval_def_CTestType_check_existence,
	conforme_mi_oval_def_CTestType_check,
	conforme_mi_oval_def_CTestType_state_operator,
	conforme_mi_oval_def_CTestType_comment,
	conforme_mi_oval_def_CTestType_deprecated,
	conforme_mi_oval_def_CTestType_Signature,
	conforme_mi_oval_def_CTestType_notes,
	conforme_mi_oval_def_CTestType_notes2,
	conforme_mi_oval_def_last_CTestType,
};
enum
{
	conforme_mi_oval_def_first_CTestsType = conforme_mi_oval_def_last_CTestType,
	conforme_mi_oval_def_last_CTestsType = conforme_mi_oval_def_first_CTestsType,
};
enum
{
	conforme_mi_oval_def_first_CTimeDifferenceFunctionType = conforme_mi_oval_def_last_CTestsType,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_format_1 = conforme_mi_oval_def_first_CTimeDifferenceFunctionType,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_format_2,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_object_component,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_variable_component,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_literal_component,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_arithmetic,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_begin,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_concat,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_end,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_escape_regex,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_split,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_substring,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_time_difference,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_regex_capture,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_unique,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_count,
	conforme_mi_oval_def_CTimeDifferenceFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CTimeDifferenceFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CUniqueFunctionType = conforme_mi_oval_def_last_CTimeDifferenceFunctionType,
	conforme_mi_oval_def_CUniqueFunctionType_object_component = conforme_mi_oval_def_first_CUniqueFunctionType,
	conforme_mi_oval_def_CUniqueFunctionType_variable_component,
	conforme_mi_oval_def_CUniqueFunctionType_literal_component,
	conforme_mi_oval_def_CUniqueFunctionType_arithmetic,
	conforme_mi_oval_def_CUniqueFunctionType_begin,
	conforme_mi_oval_def_CUniqueFunctionType_concat,
	conforme_mi_oval_def_CUniqueFunctionType_end,
	conforme_mi_oval_def_CUniqueFunctionType_escape_regex,
	conforme_mi_oval_def_CUniqueFunctionType_split,
	conforme_mi_oval_def_CUniqueFunctionType_substring,
	conforme_mi_oval_def_CUniqueFunctionType_time_difference,
	conforme_mi_oval_def_CUniqueFunctionType_regex_capture,
	conforme_mi_oval_def_CUniqueFunctionType_unique,
	conforme_mi_oval_def_CUniqueFunctionType_count,
	conforme_mi_oval_def_CUniqueFunctionType_glob_to_regex,
	conforme_mi_oval_def_last_CUniqueFunctionType,
};
enum
{
	conforme_mi_oval_def_first_CValueType = conforme_mi_oval_def_last_CUniqueFunctionType,
	conforme_mi_oval_def_CValueType_unnamed = conforme_mi_oval_def_first_CValueType,
	conforme_mi_oval_def_last_CValueType,
};
enum
{
	conforme_mi_oval_def_first_CVariableComponentType = conforme_mi_oval_def_last_CValueType,
	conforme_mi_oval_def_CVariableComponentType_var_ref = conforme_mi_oval_def_first_CVariableComponentType,
	conforme_mi_oval_def_last_CVariableComponentType,
};
enum
{
	conforme_mi_oval_def_first_CVariableType = conforme_mi_oval_def_last_CVariableComponentType,
	conforme_mi_oval_def_CVariableType_id = conforme_mi_oval_def_first_CVariableType,
	conforme_mi_oval_def_CVariableType_version,
	conforme_mi_oval_def_CVariableType_datatype,
	conforme_mi_oval_def_CVariableType_comment,
	conforme_mi_oval_def_CVariableType_deprecated,
	conforme_mi_oval_def_CVariableType_Signature,
	conforme_mi_oval_def_CVariableType_notes,
	conforme_mi_oval_def_CVariableType_notes2,
	conforme_mi_oval_def_last_CVariableType,
};
enum
{
	conforme_mi_oval_def_first_CVariablesType = conforme_mi_oval_def_last_CVariableType,
	conforme_mi_oval_def_CVariablesType_constant_variable = conforme_mi_oval_def_first_CVariablesType,
	conforme_mi_oval_def_CVariablesType_external_variable,
	conforme_mi_oval_def_CVariablesType_local_variable,
	conforme_mi_oval_def_last_CVariablesType,
};
enum
{
	conforme_mi_oval_def_first_Coval_definitions_schema = conforme_mi_oval_def_last_CVariablesType,
	conforme_mi_oval_def_Coval_definitions_schema_deprecated_info = conforme_mi_oval_def_first_Coval_definitions_schema,
	conforme_mi_oval_def_Coval_definitions_schema_element_mapping,
	conforme_mi_oval_def_Coval_definitions_schema_notes,
	conforme_mi_oval_def_Coval_definitions_schema_constant_variable,
	conforme_mi_oval_def_Coval_definitions_schema_definition,
	conforme_mi_oval_def_Coval_definitions_schema_external_variable,
	conforme_mi_oval_def_Coval_definitions_schema_filter,
	conforme_mi_oval_def_Coval_definitions_schema_local_variable,
	conforme_mi_oval_def_Coval_definitions_schema_notes2,
	conforme_mi_oval_def_Coval_definitions_schema_object,
	conforme_mi_oval_def_Coval_definitions_schema_oval_definitions,
	conforme_mi_oval_def_Coval_definitions_schema_set,
	conforme_mi_oval_def_Coval_definitions_schema_state,
	conforme_mi_oval_def_Coval_definitions_schema_test,
	conforme_mi_oval_def_Coval_definitions_schema_variable,
	conforme_mi_oval_def_Coval_definitions_schema_CanonicalizationMethod,
	conforme_mi_oval_def_Coval_definitions_schema_DSAKeyValue,
	conforme_mi_oval_def_Coval_definitions_schema_DigestMethod,
	conforme_mi_oval_def_Coval_definitions_schema_DigestValue,
	conforme_mi_oval_def_Coval_definitions_schema_KeyInfo,
	conforme_mi_oval_def_Coval_definitions_schema_KeyName,
	conforme_mi_oval_def_Coval_definitions_schema_KeyValue,
	conforme_mi_oval_def_Coval_definitions_schema_Manifest,
	conforme_mi_oval_def_Coval_definitions_schema_MgmtData,
	conforme_mi_oval_def_Coval_definitions_schema_Object2,
	conforme_mi_oval_def_Coval_definitions_schema_PGPData,
	conforme_mi_oval_def_Coval_definitions_schema_RSAKeyValue,
	conforme_mi_oval_def_Coval_definitions_schema_Reference,
	conforme_mi_oval_def_Coval_definitions_schema_RetrievalMethod,
	conforme_mi_oval_def_Coval_definitions_schema_SPKIData,
	conforme_mi_oval_def_Coval_definitions_schema_Signature,
	conforme_mi_oval_def_Coval_definitions_schema_SignatureMethod,
	conforme_mi_oval_def_Coval_definitions_schema_SignatureProperties,
	conforme_mi_oval_def_Coval_definitions_schema_SignatureProperty,
	conforme_mi_oval_def_Coval_definitions_schema_SignatureValue,
	conforme_mi_oval_def_Coval_definitions_schema_SignedInfo,
	conforme_mi_oval_def_Coval_definitions_schema_Transform,
	conforme_mi_oval_def_Coval_definitions_schema_Transforms,
	conforme_mi_oval_def_Coval_definitions_schema_X509Data,
	conforme_mi_oval_def_last_Coval_definitions_schema,
};
enum
{
	conforme_mi_oval_def_first_Cconstant_variableType = conforme_mi_oval_def_last_Coval_definitions_schema,
	conforme_mi_oval_def_Cconstant_variableType_id = conforme_mi_oval_def_first_Cconstant_variableType,
	conforme_mi_oval_def_Cconstant_variableType_version,
	conforme_mi_oval_def_Cconstant_variableType_datatype,
	conforme_mi_oval_def_Cconstant_variableType_comment,
	conforme_mi_oval_def_Cconstant_variableType_deprecated,
	conforme_mi_oval_def_Cconstant_variableType_Signature,
	conforme_mi_oval_def_Cconstant_variableType_notes,
	conforme_mi_oval_def_Cconstant_variableType_notes2,
	conforme_mi_oval_def_Cconstant_variableType_value2,
	conforme_mi_oval_def_last_Cconstant_variableType,
};
enum
{
	conforme_mi_oval_def_first_CnotesType = conforme_mi_oval_def_last_Cconstant_variableType,
	conforme_mi_oval_def_CnotesType_note = conforme_mi_oval_def_first_CnotesType,
	conforme_mi_oval_def_CnotesType_note2,
	conforme_mi_oval_def_last_CnotesType,
};
enum
{
	conforme_mi_oval_def_first_Cexternal_variableType = conforme_mi_oval_def_last_CnotesType,
	conforme_mi_oval_def_Cexternal_variableType_id = conforme_mi_oval_def_first_Cexternal_variableType,
	conforme_mi_oval_def_Cexternal_variableType_version,
	conforme_mi_oval_def_Cexternal_variableType_datatype,
	conforme_mi_oval_def_Cexternal_variableType_comment,
	conforme_mi_oval_def_Cexternal_variableType_deprecated,
	conforme_mi_oval_def_Cexternal_variableType_Signature,
	conforme_mi_oval_def_Cexternal_variableType_notes,
	conforme_mi_oval_def_Cexternal_variableType_notes2,
	conforme_mi_oval_def_Cexternal_variableType_possible_value,
	conforme_mi_oval_def_Cexternal_variableType_possible_restriction,
	conforme_mi_oval_def_last_Cexternal_variableType,
};
enum
{
	conforme_mi_oval_def_first_CfilterType = conforme_mi_oval_def_last_Cexternal_variableType,
	conforme_mi_oval_def_CfilterType_unnamed = conforme_mi_oval_def_first_CfilterType,
	conforme_mi_oval_def_CfilterType_action,
	conforme_mi_oval_def_last_CfilterType,
};
enum
{
	conforme_mi_oval_def_first_Clocal_variableType = conforme_mi_oval_def_last_CfilterType,
	conforme_mi_oval_def_Clocal_variableType_id = conforme_mi_oval_def_first_Clocal_variableType,
	conforme_mi_oval_def_Clocal_variableType_version,
	conforme_mi_oval_def_Clocal_variableType_datatype,
	conforme_mi_oval_def_Clocal_variableType_comment,
	conforme_mi_oval_def_Clocal_variableType_deprecated,
	conforme_mi_oval_def_Clocal_variableType_Signature,
	conforme_mi_oval_def_Clocal_variableType_notes,
	conforme_mi_oval_def_Clocal_variableType_notes2,
	conforme_mi_oval_def_Clocal_variableType_object_component,
	conforme_mi_oval_def_Clocal_variableType_variable_component,
	conforme_mi_oval_def_Clocal_variableType_literal_component,
	conforme_mi_oval_def_Clocal_variableType_arithmetic,
	conforme_mi_oval_def_Clocal_variableType_begin,
	conforme_mi_oval_def_Clocal_variableType_concat,
	conforme_mi_oval_def_Clocal_variableType_end,
	conforme_mi_oval_def_Clocal_variableType_escape_regex,
	conforme_mi_oval_def_Clocal_variableType_split,
	conforme_mi_oval_def_Clocal_variableType_substring,
	conforme_mi_oval_def_Clocal_variableType_time_difference,
	conforme_mi_oval_def_Clocal_variableType_regex_capture,
	conforme_mi_oval_def_Clocal_variableType_unique,
	conforme_mi_oval_def_Clocal_variableType_count,
	conforme_mi_oval_def_Clocal_variableType_glob_to_regex,
	conforme_mi_oval_def_last_Clocal_variableType,
};
enum
{
	conforme_mi_oval_def_first_Coval_definitionsType = conforme_mi_oval_def_last_Clocal_variableType,
	conforme_mi_oval_def_Coval_definitionsType_generator = conforme_mi_oval_def_first_Coval_definitionsType,
	conforme_mi_oval_def_Coval_definitionsType_definitions,
	conforme_mi_oval_def_Coval_definitionsType_tests,
	conforme_mi_oval_def_Coval_definitionsType_objects,
	conforme_mi_oval_def_Coval_definitionsType_states,
	conforme_mi_oval_def_Coval_definitionsType_variables,
	conforme_mi_oval_def_Coval_definitionsType_Signature,
	conforme_mi_oval_def_last_Coval_definitionsType,
};
enum
{
	conforme_mi_oval_def_first_CsetType = conforme_mi_oval_def_last_Coval_definitionsType,
	conforme_mi_oval_def_CsetType_set_operator = conforme_mi_oval_def_first_CsetType,
	conforme_mi_oval_def_CsetType_set,
	conforme_mi_oval_def_CsetType_object_reference,
	conforme_mi_oval_def_CsetType_filter,
	conforme_mi_oval_def_last_CsetType,
};
enum
{
	conforme_mi_oval_def_first_CnameType = conforme_mi_oval_def_last_CsetType,
	conforme_mi_oval_def_last_CnameType = conforme_mi_oval_def_first_CnameType,
};
enum
{
	conforme_mi_oval_def_first_CdatatypeType = conforme_mi_oval_def_last_CnameType,
	conforme_mi_oval_def_last_CdatatypeType = conforme_mi_oval_def_first_CdatatypeType,
};
enum
{
	conforme_mi_oval_def_first_CdatatypeType2 = conforme_mi_oval_def_last_CdatatypeType,
	conforme_mi_oval_def_last_CdatatypeType2 = conforme_mi_oval_def_first_CdatatypeType2,
};
enum
{
	conforme_mi_oval_def_first_CnameType2 = conforme_mi_oval_def_last_CdatatypeType2,
	conforme_mi_oval_def_last_CnameType2 = conforme_mi_oval_def_first_CnameType2,
};
enum
{
	conforme_mi_oval_def_first_CdatatypeType3 = conforme_mi_oval_def_last_CnameType2,
	conforme_mi_oval_def_last_CdatatypeType3 = conforme_mi_oval_def_first_CdatatypeType3,
};
enum
{
	conforme_mi_oval_def_first_CdatatypeType4 = conforme_mi_oval_def_last_CdatatypeType3,
	conforme_mi_oval_def_last_CdatatypeType4 = conforme_mi_oval_def_first_CdatatypeType4,
};
enum
{
	conforme_mi_oval_def_first_CdatatypeType5 = conforme_mi_oval_def_last_CdatatypeType4,
	conforme_mi_oval_def_last_CdatatypeType5 = conforme_mi_oval_def_first_CdatatypeType5,
};
enum
{
	conforme_mi_xmldsig_first_CCanonicalizationMethodType = conforme_mi_oval_def_last_CdatatypeType5,
	conforme_mi_xmldsig_CCanonicalizationMethodType_Algorithm = conforme_mi_xmldsig_first_CCanonicalizationMethodType,
	conforme_mi_xmldsig_CCanonicalizationMethodType_unnamed,
	conforme_mi_xmldsig_last_CCanonicalizationMethodType,
};
enum
{
	conforme_mi_xmldsig_first_CCryptoBinary = conforme_mi_xmldsig_last_CCanonicalizationMethodType,
	conforme_mi_xmldsig_last_CCryptoBinary = conforme_mi_xmldsig_first_CCryptoBinary,
};
enum
{
	conforme_mi_xmldsig_first_CDSAKeyValueType = conforme_mi_xmldsig_last_CCryptoBinary,
	conforme_mi_xmldsig_CDSAKeyValueType_P = conforme_mi_xmldsig_first_CDSAKeyValueType,
	conforme_mi_xmldsig_CDSAKeyValueType_Q,
	conforme_mi_xmldsig_CDSAKeyValueType_G,
	conforme_mi_xmldsig_CDSAKeyValueType_Y,
	conforme_mi_xmldsig_CDSAKeyValueType_J,
	conforme_mi_xmldsig_CDSAKeyValueType_Seed,
	conforme_mi_xmldsig_CDSAKeyValueType_PgenCounter,
	conforme_mi_xmldsig_last_CDSAKeyValueType,
};
enum
{
	conforme_mi_xmldsig_first_CDigestMethodType = conforme_mi_xmldsig_last_CDSAKeyValueType,
	conforme_mi_xmldsig_CDigestMethodType_Algorithm = conforme_mi_xmldsig_first_CDigestMethodType,
	conforme_mi_xmldsig_CDigestMethodType_unnamed,
	conforme_mi_xmldsig_last_CDigestMethodType,
};
enum
{
	conforme_mi_xmldsig_first_CDigestValueType = conforme_mi_xmldsig_last_CDigestMethodType,
	conforme_mi_xmldsig_last_CDigestValueType = conforme_mi_xmldsig_first_CDigestValueType,
};
enum
{
	conforme_mi_xmldsig_first_CHMACOutputLengthType = conforme_mi_xmldsig_last_CDigestValueType,
	conforme_mi_xmldsig_last_CHMACOutputLengthType = conforme_mi_xmldsig_first_CHMACOutputLengthType,
};
enum
{
	conforme_mi_xmldsig_first_CKeyInfoType = conforme_mi_xmldsig_last_CHMACOutputLengthType,
	conforme_mi_xmldsig_CKeyInfoType_Id = conforme_mi_xmldsig_first_CKeyInfoType,
	conforme_mi_xmldsig_CKeyInfoType_unnamed,
	conforme_mi_xmldsig_CKeyInfoType_KeyName,
	conforme_mi_xmldsig_CKeyInfoType_KeyValue,
	conforme_mi_xmldsig_CKeyInfoType_RetrievalMethod,
	conforme_mi_xmldsig_CKeyInfoType_X509Data,
	conforme_mi_xmldsig_CKeyInfoType_PGPData,
	conforme_mi_xmldsig_CKeyInfoType_SPKIData,
	conforme_mi_xmldsig_CKeyInfoType_MgmtData,
	conforme_mi_xmldsig_last_CKeyInfoType,
};
enum
{
	conforme_mi_xmldsig_first_CKeyValueType = conforme_mi_xmldsig_last_CKeyInfoType,
	conforme_mi_xmldsig_CKeyValueType_unnamed = conforme_mi_xmldsig_first_CKeyValueType,
	conforme_mi_xmldsig_CKeyValueType_DSAKeyValue,
	conforme_mi_xmldsig_CKeyValueType_RSAKeyValue,
	conforme_mi_xmldsig_last_CKeyValueType,
};
enum
{
	conforme_mi_xmldsig_first_CManifestType = conforme_mi_xmldsig_last_CKeyValueType,
	conforme_mi_xmldsig_CManifestType_Id = conforme_mi_xmldsig_first_CManifestType,
	conforme_mi_xmldsig_CManifestType_Reference,
	conforme_mi_xmldsig_last_CManifestType,
};
enum
{
	conforme_mi_xmldsig_first_CObjectType = conforme_mi_xmldsig_last_CManifestType,
	conforme_mi_xmldsig_CObjectType_Id = conforme_mi_xmldsig_first_CObjectType,
	conforme_mi_xmldsig_CObjectType_MimeType,
	conforme_mi_xmldsig_CObjectType_Encoding,
	conforme_mi_xmldsig_CObjectType_unnamed,
	conforme_mi_xmldsig_last_CObjectType,
};
enum
{
	conforme_mi_xmldsig_first_CPGPDataType = conforme_mi_xmldsig_last_CObjectType,
	conforme_mi_xmldsig_CPGPDataType_PGPKeyID = conforme_mi_xmldsig_first_CPGPDataType,
	conforme_mi_xmldsig_CPGPDataType_PGPKeyPacket,
	conforme_mi_xmldsig_last_CPGPDataType,
};
enum
{
	conforme_mi_xmldsig_first_CRSAKeyValueType = conforme_mi_xmldsig_last_CPGPDataType,
	conforme_mi_xmldsig_CRSAKeyValueType_Modulus = conforme_mi_xmldsig_first_CRSAKeyValueType,
	conforme_mi_xmldsig_CRSAKeyValueType_Exponent,
	conforme_mi_xmldsig_last_CRSAKeyValueType,
};
enum
{
	conforme_mi_xmldsig_first_CReferenceType = conforme_mi_xmldsig_last_CRSAKeyValueType,
	conforme_mi_xmldsig_CReferenceType_Id = conforme_mi_xmldsig_first_CReferenceType,
	conforme_mi_xmldsig_CReferenceType_URI,
	conforme_mi_xmldsig_CReferenceType_Type,
	conforme_mi_xmldsig_CReferenceType_Transforms,
	conforme_mi_xmldsig_CReferenceType_DigestMethod,
	conforme_mi_xmldsig_CReferenceType_DigestValue,
	conforme_mi_xmldsig_last_CReferenceType,
};
enum
{
	conforme_mi_xmldsig_first_CRetrievalMethodType = conforme_mi_xmldsig_last_CReferenceType,
	conforme_mi_xmldsig_CRetrievalMethodType_URI = conforme_mi_xmldsig_first_CRetrievalMethodType,
	conforme_mi_xmldsig_CRetrievalMethodType_Type,
	conforme_mi_xmldsig_CRetrievalMethodType_Transforms,
	conforme_mi_xmldsig_last_CRetrievalMethodType,
};
enum
{
	conforme_mi_xmldsig_first_CSPKIDataType = conforme_mi_xmldsig_last_CRetrievalMethodType,
	conforme_mi_xmldsig_CSPKIDataType_SPKISexp = conforme_mi_xmldsig_first_CSPKIDataType,
	conforme_mi_xmldsig_last_CSPKIDataType,
};
enum
{
	conforme_mi_xmldsig_first_CSignatureMethodType = conforme_mi_xmldsig_last_CSPKIDataType,
	conforme_mi_xmldsig_CSignatureMethodType_Algorithm = conforme_mi_xmldsig_first_CSignatureMethodType,
	conforme_mi_xmldsig_CSignatureMethodType_unnamed,
	conforme_mi_xmldsig_CSignatureMethodType_HMACOutputLength,
	conforme_mi_xmldsig_last_CSignatureMethodType,
};
enum
{
	conforme_mi_xmldsig_first_CSignaturePropertiesType = conforme_mi_xmldsig_last_CSignatureMethodType,
	conforme_mi_xmldsig_CSignaturePropertiesType_Id = conforme_mi_xmldsig_first_CSignaturePropertiesType,
	conforme_mi_xmldsig_CSignaturePropertiesType_SignatureProperty,
	conforme_mi_xmldsig_last_CSignaturePropertiesType,
};
enum
{
	conforme_mi_xmldsig_first_CSignaturePropertyType = conforme_mi_xmldsig_last_CSignaturePropertiesType,
	conforme_mi_xmldsig_CSignaturePropertyType_Target = conforme_mi_xmldsig_first_CSignaturePropertyType,
	conforme_mi_xmldsig_CSignaturePropertyType_Id,
	conforme_mi_xmldsig_CSignaturePropertyType_unnamed,
	conforme_mi_xmldsig_last_CSignaturePropertyType,
};
enum
{
	conforme_mi_xmldsig_first_CSignatureType = conforme_mi_xmldsig_last_CSignaturePropertyType,
	conforme_mi_xmldsig_CSignatureType_Id = conforme_mi_xmldsig_first_CSignatureType,
	conforme_mi_xmldsig_CSignatureType_SignedInfo,
	conforme_mi_xmldsig_CSignatureType_SignatureValue,
	conforme_mi_xmldsig_CSignatureType_KeyInfo,
	conforme_mi_xmldsig_CSignatureType_Object,
	conforme_mi_xmldsig_last_CSignatureType,
};
enum
{
	conforme_mi_xmldsig_first_CSignatureValueType = conforme_mi_xmldsig_last_CSignatureType,
	conforme_mi_xmldsig_CSignatureValueType_unnamed = conforme_mi_xmldsig_first_CSignatureValueType,
	conforme_mi_xmldsig_CSignatureValueType_Id,
	conforme_mi_xmldsig_last_CSignatureValueType,
};
enum
{
	conforme_mi_xmldsig_first_CSignedInfoType = conforme_mi_xmldsig_last_CSignatureValueType,
	conforme_mi_xmldsig_CSignedInfoType_Id = conforme_mi_xmldsig_first_CSignedInfoType,
	conforme_mi_xmldsig_CSignedInfoType_CanonicalizationMethod,
	conforme_mi_xmldsig_CSignedInfoType_SignatureMethod,
	conforme_mi_xmldsig_CSignedInfoType_Reference,
	conforme_mi_xmldsig_last_CSignedInfoType,
};
enum
{
	conforme_mi_xmldsig_first_CTransformType = conforme_mi_xmldsig_last_CSignedInfoType,
	conforme_mi_xmldsig_CTransformType_Algorithm = conforme_mi_xmldsig_first_CTransformType,
	conforme_mi_xmldsig_CTransformType_unnamed,
	conforme_mi_xmldsig_CTransformType_XPath,
	conforme_mi_xmldsig_last_CTransformType,
};
enum
{
	conforme_mi_xmldsig_first_CTransformsType = conforme_mi_xmldsig_last_CTransformType,
	conforme_mi_xmldsig_CTransformsType_Transform = conforme_mi_xmldsig_first_CTransformsType,
	conforme_mi_xmldsig_last_CTransformsType,
};
enum
{
	conforme_mi_xmldsig_first_CX509DataType = conforme_mi_xmldsig_last_CTransformsType,
	conforme_mi_xmldsig_CX509DataType_X509IssuerSerial = conforme_mi_xmldsig_first_CX509DataType,
	conforme_mi_xmldsig_CX509DataType_X509SKI,
	conforme_mi_xmldsig_CX509DataType_X509SubjectName,
	conforme_mi_xmldsig_CX509DataType_X509Certificate,
	conforme_mi_xmldsig_CX509DataType_X509CRL,
	conforme_mi_xmldsig_last_CX509DataType,
};
enum
{
	conforme_mi_xmldsig_first_CX509IssuerSerialType = conforme_mi_xmldsig_last_CX509DataType,
	conforme_mi_xmldsig_CX509IssuerSerialType_X509IssuerName = conforme_mi_xmldsig_first_CX509IssuerSerialType,
	conforme_mi_xmldsig_CX509IssuerSerialType_X509SerialNumber,
	conforme_mi_xmldsig_last_CX509IssuerSerialType,
};
enum
{
	conforme_mi_xmldsig_first_CDigestValueTypeType = conforme_mi_xmldsig_last_CX509IssuerSerialType,
	conforme_mi_xmldsig_CDigestValueTypeType_unnamed = conforme_mi_xmldsig_first_CDigestValueTypeType,
	conforme_mi_xmldsig_last_CDigestValueTypeType,
};
enum
{
	conforme_mi_xmldsig_first_CCryptoBinaryType = conforme_mi_xmldsig_last_CDigestValueTypeType,
	conforme_mi_xmldsig_CCryptoBinaryType_unnamed = conforme_mi_xmldsig_first_CCryptoBinaryType,
	conforme_mi_xmldsig_last_CCryptoBinaryType,
};
enum
{
	conforme_mi_xmldsig_first_CHMACOutputLengthTypeType = conforme_mi_xmldsig_last_CCryptoBinaryType,
	conforme_mi_xmldsig_CHMACOutputLengthTypeType_unnamed = conforme_mi_xmldsig_first_CHMACOutputLengthTypeType,
	conforme_mi_xmldsig_last_CHMACOutputLengthTypeType,
};
enum
{
	conforme_mi_xmlschema_first_CENTITIES = conforme_mi_xmldsig_last_CHMACOutputLengthTypeType,
	conforme_mi_xmlschema_last_CENTITIES = conforme_mi_xmlschema_first_CENTITIES,
};
enum
{
	conforme_mi_xmlschema_first_CENTITY = conforme_mi_xmlschema_last_CENTITIES,
	conforme_mi_xmlschema_last_CENTITY = conforme_mi_xmlschema_first_CENTITY,
};
enum
{
	conforme_mi_xmlschema_first_CID = conforme_mi_xmlschema_last_CENTITY,
	conforme_mi_xmlschema_last_CID = conforme_mi_xmlschema_first_CID,
};
enum
{
	conforme_mi_xmlschema_first_CIDREF = conforme_mi_xmlschema_last_CID,
	conforme_mi_xmlschema_last_CIDREF = conforme_mi_xmlschema_first_CIDREF,
};
enum
{
	conforme_mi_xmlschema_first_CIDREFS = conforme_mi_xmlschema_last_CIDREF,
	conforme_mi_xmlschema_last_CIDREFS = conforme_mi_xmlschema_first_CIDREFS,
};
enum
{
	conforme_mi_xmlschema_first_CNCName = conforme_mi_xmlschema_last_CIDREFS,
	conforme_mi_xmlschema_last_CNCName = conforme_mi_xmlschema_first_CNCName,
};
enum
{
	conforme_mi_xmlschema_first_CNMTOKEN = conforme_mi_xmlschema_last_CNCName,
	conforme_mi_xmlschema_last_CNMTOKEN = conforme_mi_xmlschema_first_CNMTOKEN,
};
enum
{
	conforme_mi_xmlschema_first_CNMTOKENS = conforme_mi_xmlschema_last_CNMTOKEN,
	conforme_mi_xmlschema_last_CNMTOKENS = conforme_mi_xmlschema_first_CNMTOKENS,
};
enum
{
	conforme_mi_xmlschema_first_CNOTATION = conforme_mi_xmlschema_last_CNMTOKENS,
	conforme_mi_xmlschema_last_CNOTATION = conforme_mi_xmlschema_first_CNOTATION,
};
enum
{
	conforme_mi_xmlschema_first_CName = conforme_mi_xmlschema_last_CNOTATION,
	conforme_mi_xmlschema_last_CName = conforme_mi_xmlschema_first_CName,
};
enum
{
	conforme_mi_xmlschema_first_CQName = conforme_mi_xmlschema_last_CName,
	conforme_mi_xmlschema_last_CQName = conforme_mi_xmlschema_first_CQName,
};
enum
{
	conforme_mi_xmlschema_first_CanySimpleType = conforme_mi_xmlschema_last_CQName,
	conforme_mi_xmlschema_last_CanySimpleType = conforme_mi_xmlschema_first_CanySimpleType,
};
enum
{
	conforme_mi_xmlschema_first_CanyType = conforme_mi_xmlschema_last_CanySimpleType,
	conforme_mi_xmlschema_CanyType_unnamed = conforme_mi_xmlschema_first_CanyType,
	conforme_mi_xmlschema_last_CanyType,
};
enum
{
	conforme_mi_xmlschema_first_CanyURI = conforme_mi_xmlschema_last_CanyType,
	conforme_mi_xmlschema_last_CanyURI = conforme_mi_xmlschema_first_CanyURI,
};
enum
{
	conforme_mi_xmlschema_first_Cbase64Binary = conforme_mi_xmlschema_last_CanyURI,
	conforme_mi_xmlschema_last_Cbase64Binary = conforme_mi_xmlschema_first_Cbase64Binary,
};
enum
{
	conforme_mi_xmlschema_first_Cboolean = conforme_mi_xmlschema_last_Cbase64Binary,
	conforme_mi_xmlschema_last_Cboolean = conforme_mi_xmlschema_first_Cboolean,
};
enum
{
	conforme_mi_xmlschema_first_Cbyte = conforme_mi_xmlschema_last_Cboolean,
	conforme_mi_xmlschema_last_Cbyte = conforme_mi_xmlschema_first_Cbyte,
};
enum
{
	conforme_mi_xmlschema_first_Cdate = conforme_mi_xmlschema_last_Cbyte,
	conforme_mi_xmlschema_last_Cdate = conforme_mi_xmlschema_first_Cdate,
};
enum
{
	conforme_mi_xmlschema_first_CdateTime = conforme_mi_xmlschema_last_Cdate,
	conforme_mi_xmlschema_last_CdateTime = conforme_mi_xmlschema_first_CdateTime,
};
enum
{
	conforme_mi_xmlschema_first_Cdecimal = conforme_mi_xmlschema_last_CdateTime,
	conforme_mi_xmlschema_last_Cdecimal = conforme_mi_xmlschema_first_Cdecimal,
};
enum
{
	conforme_mi_xmlschema_first_Cdouble = conforme_mi_xmlschema_last_Cdecimal,
	conforme_mi_xmlschema_last_Cdouble = conforme_mi_xmlschema_first_Cdouble,
};
enum
{
	conforme_mi_xmlschema_first_Cduration = conforme_mi_xmlschema_last_Cdouble,
	conforme_mi_xmlschema_last_Cduration = conforme_mi_xmlschema_first_Cduration,
};
enum
{
	conforme_mi_xmlschema_first_Cfloat = conforme_mi_xmlschema_last_Cduration,
	conforme_mi_xmlschema_last_Cfloat = conforme_mi_xmlschema_first_Cfloat,
};
enum
{
	conforme_mi_xmlschema_first_CgDay = conforme_mi_xmlschema_last_Cfloat,
	conforme_mi_xmlschema_last_CgDay = conforme_mi_xmlschema_first_CgDay,
};
enum
{
	conforme_mi_xmlschema_first_CgMonth = conforme_mi_xmlschema_last_CgDay,
	conforme_mi_xmlschema_last_CgMonth = conforme_mi_xmlschema_first_CgMonth,
};
enum
{
	conforme_mi_xmlschema_first_CgMonthDay = conforme_mi_xmlschema_last_CgMonth,
	conforme_mi_xmlschema_last_CgMonthDay = conforme_mi_xmlschema_first_CgMonthDay,
};
enum
{
	conforme_mi_xmlschema_first_CgYear = conforme_mi_xmlschema_last_CgMonthDay,
	conforme_mi_xmlschema_last_CgYear = conforme_mi_xmlschema_first_CgYear,
};
enum
{
	conforme_mi_xmlschema_first_CgYearMonth = conforme_mi_xmlschema_last_CgYear,
	conforme_mi_xmlschema_last_CgYearMonth = conforme_mi_xmlschema_first_CgYearMonth,
};
enum
{
	conforme_mi_xmlschema_first_ChexBinary = conforme_mi_xmlschema_last_CgYearMonth,
	conforme_mi_xmlschema_last_ChexBinary = conforme_mi_xmlschema_first_ChexBinary,
};
enum
{
	conforme_mi_xmlschema_first_Cint = conforme_mi_xmlschema_last_ChexBinary,
	conforme_mi_xmlschema_last_Cint = conforme_mi_xmlschema_first_Cint,
};
enum
{
	conforme_mi_xmlschema_first_Cinteger = conforme_mi_xmlschema_last_Cint,
	conforme_mi_xmlschema_last_Cinteger = conforme_mi_xmlschema_first_Cinteger,
};
enum
{
	conforme_mi_xmlschema_first_Clanguage = conforme_mi_xmlschema_last_Cinteger,
	conforme_mi_xmlschema_last_Clanguage = conforme_mi_xmlschema_first_Clanguage,
};
enum
{
	conforme_mi_xmlschema_first_Clong = conforme_mi_xmlschema_last_Clanguage,
	conforme_mi_xmlschema_last_Clong = conforme_mi_xmlschema_first_Clong,
};
enum
{
	conforme_mi_xmlschema_first_CnegativeInteger = conforme_mi_xmlschema_last_Clong,
	conforme_mi_xmlschema_last_CnegativeInteger = conforme_mi_xmlschema_first_CnegativeInteger,
};
enum
{
	conforme_mi_xmlschema_first_CnonNegativeInteger = conforme_mi_xmlschema_last_CnegativeInteger,
	conforme_mi_xmlschema_last_CnonNegativeInteger = conforme_mi_xmlschema_first_CnonNegativeInteger,
};
enum
{
	conforme_mi_xmlschema_first_CnonPositiveInteger = conforme_mi_xmlschema_last_CnonNegativeInteger,
	conforme_mi_xmlschema_last_CnonPositiveInteger = conforme_mi_xmlschema_first_CnonPositiveInteger,
};
enum
{
	conforme_mi_xmlschema_first_CnormalizedString = conforme_mi_xmlschema_last_CnonPositiveInteger,
	conforme_mi_xmlschema_last_CnormalizedString = conforme_mi_xmlschema_first_CnormalizedString,
};
enum
{
	conforme_mi_xmlschema_first_CpositiveInteger = conforme_mi_xmlschema_last_CnormalizedString,
	conforme_mi_xmlschema_last_CpositiveInteger = conforme_mi_xmlschema_first_CpositiveInteger,
};
enum
{
	conforme_mi_xmlschema_first_Cshort = conforme_mi_xmlschema_last_CpositiveInteger,
	conforme_mi_xmlschema_last_Cshort = conforme_mi_xmlschema_first_Cshort,
};
enum
{
	conforme_mi_xmlschema_first_Cstring = conforme_mi_xmlschema_last_Cshort,
	conforme_mi_xmlschema_last_Cstring = conforme_mi_xmlschema_first_Cstring,
};
enum
{
	conforme_mi_xmlschema_first_Ctime = conforme_mi_xmlschema_last_Cstring,
	conforme_mi_xmlschema_last_Ctime = conforme_mi_xmlschema_first_Ctime,
};
enum
{
	conforme_mi_xmlschema_first_Ctoken = conforme_mi_xmlschema_last_Ctime,
	conforme_mi_xmlschema_last_Ctoken = conforme_mi_xmlschema_first_Ctoken,
};
enum
{
	conforme_mi_xmlschema_first_CunsignedByte = conforme_mi_xmlschema_last_Ctoken,
	conforme_mi_xmlschema_last_CunsignedByte = conforme_mi_xmlschema_first_CunsignedByte,
};
enum
{
	conforme_mi_xmlschema_first_CunsignedInt = conforme_mi_xmlschema_last_CunsignedByte,
	conforme_mi_xmlschema_last_CunsignedInt = conforme_mi_xmlschema_first_CunsignedInt,
};
enum
{
	conforme_mi_xmlschema_first_CunsignedLong = conforme_mi_xmlschema_last_CunsignedInt,
	conforme_mi_xmlschema_last_CunsignedLong = conforme_mi_xmlschema_first_CunsignedLong,
};
enum
{
	conforme_mi_xmlschema_first_CunsignedShort = conforme_mi_xmlschema_last_CunsignedLong,
	conforme_mi_xmlschema_last_CunsignedShort = conforme_mi_xmlschema_first_CunsignedShort,
};
enum
{
	conforme_mi_xmlschema_first_CstringType = conforme_mi_xmlschema_last_CunsignedShort,
	conforme_mi_xmlschema_CstringType_unnamed = conforme_mi_xmlschema_first_CstringType,
	conforme_mi_xmlschema_last_CstringType,
};
enum
{
	conforme_mi_xmlschema_first_CNCNameType = conforme_mi_xmlschema_last_CstringType,
	conforme_mi_xmlschema_CNCNameType_unnamed = conforme_mi_xmlschema_first_CNCNameType,
	conforme_mi_xmlschema_last_CNCNameType,
};
enum
{
	conforme_mi_xmlschema_first_CdateTimeType = conforme_mi_xmlschema_last_CNCNameType,
	conforme_mi_xmlschema_CdateTimeType_unnamed = conforme_mi_xmlschema_first_CdateTimeType,
	conforme_mi_xmlschema_last_CdateTimeType,
};
enum
{
	conforme_mi_xmlschema_first_CanySimpleTypeType = conforme_mi_xmlschema_last_CdateTimeType,
	conforme_mi_xmlschema_CanySimpleTypeType_unnamed = conforme_mi_xmlschema_first_CanySimpleTypeType,
	conforme_mi_xmlschema_last_CanySimpleTypeType,
};
enum
{
	conforme_mi_xmlschema_first_Cbase64BinaryType = conforme_mi_xmlschema_last_CanySimpleTypeType,
	conforme_mi_xmlschema_Cbase64BinaryType_unnamed = conforme_mi_xmlschema_first_Cbase64BinaryType,
	conforme_mi_xmlschema_last_Cbase64BinaryType,
};
enum
{
	conforme_mi_xmlschema_first_CintegerType = conforme_mi_xmlschema_last_Cbase64BinaryType,
	conforme_mi_xmlschema_CintegerType_unnamed = conforme_mi_xmlschema_first_CintegerType,
	conforme_mi_xmlschema_last_CintegerType,
};



extern CONFORME_OVAL_DECLSPECIFIER const conforme::FacetInfo facets[];
extern CONFORME_OVAL_DECLSPECIFIER const conforme::NamespaceInfo namespaces[];
extern CONFORME_OVAL_DECLSPECIFIER const conforme::MemberInfo members[];
extern CONFORME_OVAL_DECLSPECIFIER const conforme::TypeInfo types[];

}  // namespace oval_definitions_schema

#endif // _CONFORME_INCLUDED_OVAL_DEFINITIONS_SCHEMA_TYPEINFO_H_
